[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
port = 8080
sleepApplication = false

[_variables]
NODE_ENV = "production"
PORT = "8080"
