'use client';
import { useState } from 'react';
import ToolExampleClearActions from '@/components/tools/ToolExampleClearActions';
import { calculateIpRange } from '@/lib/network-tools';

export default function IpRangeCalculatorClient() {
  const [start, setStart] = useState('192.168.1.1'); const [end, setEnd] = useState('192.168.1.254'); const [result, setResult] = useState<ReturnType<typeof calculateIpRange>>(null); const [error, setError] = useState(''); const [copied, setCopied] = useState(false);
  const calculate = () => { const next = calculateIpRange(start, end); setResult(next); setError(next ? '' : 'Enter valid IPv4 addresses with the start at or before the end.'); setCopied(false); };
  const clear = () => { setStart(''); setEnd(''); setResult(null); setError(''); setCopied(false); };
  const example = () => { setStart('192.168.1.1'); setEnd('192.168.1.254'); setResult(null); setError(''); setCopied(false); };
  const copy = () => { if (!result) return; navigator.clipboard.writeText(`Range: ${result.startIp} - ${result.endIp}\nCount: ${result.count}\nCIDR: ${result.network}/${result.prefix}\nNetmask: ${result.netmask}\nNetwork: ${result.network}\nBroadcast: ${result.broadcast}`).catch(() => {}); setCopied(true); window.setTimeout(() => setCopied(false), 1500); };
  return <div><div className="tb-v2-tool-input-head"><span className="tb-v2-tool-label">IP Range</span><ToolExampleClearActions exampleCount={1} onExample={example} onClear={clear} canClear={Boolean(start || end || result || error)} /></div><div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', padding: 20 }}><input type="text" value={start} onChange={e => setStart(e.target.value)} onKeyDown={e => e.key === 'Enter' && calculate()} placeholder="Start IP" className="tb-v2-input" style={{ flex: '1 1 220px', fontFamily: 'var(--f-mono)' }} aria-label="Start IP" /><input type="text" value={end} onChange={e => setEnd(e.target.value)} onKeyDown={e => e.key === 'Enter' && calculate()} placeholder="End IP" className="tb-v2-input" style={{ flex: '1 1 220px', fontFamily: 'var(--f-mono)' }} aria-label="End IP" /><button type="button" onClick={calculate} className="tb-v2-btn tb-v2-btn-primary">Calculate</button></div>{error && <div style={{ color: '#ef4444', padding: '0 20px 12px', fontSize: 13 }}>{error}</div>}{result && <><div className="tb-v2-tool-output-head"><span className="tb-v2-tool-label">Results</span><button type="button" onClick={copy} className={`tb-v2-copy-btn ${copied ? 'done' : ''}`}>{copied ? 'Copied' : 'Copy'}</button></div><div className="tb-v2-tool-output-body">{[['First IP', result.firstIp], ['Last IP', result.lastIp], ['Inclusive Address Count', result.count.toLocaleString()], ['Smallest Enclosing CIDR', `${result.network}/${result.prefix}`], ['Netmask', result.netmask], ['Network Address', result.network], ['Broadcast Address', result.broadcast]].map(([label, value]) => <div key={label} style={{ display: 'flex', justifyContent: 'space-between', gap: 16, padding: '10px 0', borderBottom: '1px solid var(--tb-border)' }}><span style={{ color: 'var(--tb-text-secondary)', fontSize: 13 }}>{label}</span><span style={{ fontFamily: 'var(--f-mono)' }}>{value}</span></div>)}</div></>}</div>;
}
