'use client';
import { useMemo, useState } from 'react';
import { toPython, toTypescript, diffLines, parseJson } from '@/lib/developer-data/core';
import { jsonPath } from '@/lib/developer-data/jsonpath';
import { validateSchema } from '@/lib/developer-data/schema';
import { formatSql } from '@/lib/developer-data/sql';
import { formatXml, minifyXml, xmlDocument, htmlToJsx } from '@/lib/developer-data/browser';
import { Actions, DataShell, TextInput, Result, attempt } from './DataUi';
const JSON_EXAMPLE = '{"name":"Ada","active":true,"items":[1,null,{"label":"two"}]}';
export function PythonTool() { const [input, setInput] = useState(''); const result = useMemo(() => attempt(() => input.trim() ? toPython(input) : ''), [input]); return <DataShell><Actions example={() => setInput(JSON_EXAMPLE)} clear={() => setInput('')}/><TextInput label="JSON input" value={input} onChange={setInput}/><Result {...result}/></DataShell>; }
export function TypescriptTool() {
    const [input, setInput] = useState(''), [root, setRoot] = useState('Root'), [item, setItem] = useState('Data'), [single, setSingle] = useState(true), [semi, setSemi] = useState(true);
    const result = useMemo(() => attempt(() => input.trim() ? toTypescript(input, root, item, single, semi) : ''), [input, root, item, single, semi]);
    return <DataShell><Actions example={() => setInput(JSON_EXAMPLE)} clear={() => { setInput(''); setRoot('Root'); setItem('Data'); setSingle(true); setSemi(true); }}/><TextInput label="JSON input" value={input} onChange={setInput}/><label>Root type name<input className="tb-v2-input" aria-label="Root type name" value={root} maxLength={100} onChange={e => setRoot(e.target.value)}/></label><label>Array item type name<input className="tb-v2-input" aria-label="Array item type name" value={item} maxLength={100} onChange={e => setItem(e.target.value)}/></label><label><input type="checkbox" checked={single} onChange={e => setSingle(e.target.checked)}/> Single quotes</label><label><input type="checkbox" checked={semi} onChange={e => setSemi(e.target.checked)}/> Semicolons</label><Result {...result}/></DataShell>;
}
const PATH_EXAMPLE = '{"store":{"book":[{"title":"One","price":5},{"title":"Two","price":25}]}}';
export function PathTool() { const [input, setInput] = useState(''), [path, setPath] = useState('$.store.book[*].title'); const result = useMemo(() => attempt(() => input.trim() ? JSON.stringify(jsonPath(input, path), null, 2) : ''), [input, path]); return <DataShell><Actions example={() => { setInput(PATH_EXAMPLE); setPath('$.store.book[*].title'); }} clear={() => { setInput(''); setPath(''); }}/><TextInput label="JSON input" value={input} onChange={setInput}/><label>JSONPath expression<input aria-label="JSONPath expression" className="tb-v2-input" value={path} onChange={e => setPath(e.target.value)}/></label><div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>{['$.store.book[*]', '$.store.book[*].title', '$..book[?(@.price > 20)]'].map(p => <button key={p} className="tb-v2-btn tb-v2-btn-sm" onClick={() => setPath(p)}>{p}</button>)}</div><p>Supports root, dot and quoted keys, indexes, wildcards, recursive descent and simple property comparisons. Other expressions return an error. Results are a JSON array; [] means no matches.</p><Result {...result}/></DataShell>; }
function prettyJson(text:string) { try { return JSON.stringify(parseJson(text), null, 2); } catch { return text; } }
export function SchemaTool() { const [input, setInput] = useState(''), [schema, setSchema] = useState(''); const result = useMemo(() => attempt(() => { if (!input.trim() && !schema.trim())
    return ''; if (!input.trim() || !schema.trim())
    throw new Error('Both JSON and schema are required.'); const errors = validateSchema(input, schema); if (errors.length)
    throw new Error(errors.join('\n')); return 'Valid against the supported schema.'; }), [input, schema]); return <DataShell><Actions example={() => { setInput('{"name":"Ada","age":36}'); setSchema('{"type":"object","required":["name"],"properties":{"name":{"type":"string"},"age":{"type":"integer","minimum":0}},"additionalProperties":false}'); }} clear={() => { setInput(''); setSchema(''); }}/><button className="tb-v2-btn" onClick={() => setSchema(prettyJson(schema))}>Format schema</button><TextInput label="JSON schema" value={schema} onChange={setSchema}/><button className="tb-v2-btn" onClick={() => setInput(prettyJson(input))}>Format JSON</button><TextInput label="JSON input" value={input} onChange={setInput}/><p>Draft-07 subset: types, enum/const, numeric and length bounds, objects, arrays and logical combinations. References, patterns, formats, tuple items and other unsupported keywords return an error; they are never silently accepted.</p><Result {...result}/></DataShell>; }
export function SqlTool() { const [input, setInput] = useState(''), [upper, setUpper] = useState(true), [indent, setIndent] = useState(2); const result = useMemo(() => attempt(() => formatSql(input, upper, indent)), [input, upper, indent]); return <DataShell><Actions example={() => setInput("select id, 'from  here' as label from users where active = 1;")} clear={() => { setInput(''); setUpper(true); setIndent(2); }}/><TextInput label="SQL input" value={input} onChange={setInput}/><label><input type="checkbox" checked={upper} onChange={e => setUpper(e.target.checked)}/> Uppercase keywords</label><label>Indent<select aria-label="Indent" className="tb-v2-input" value={indent} onChange={e => setIndent(Number(e.target.value))}><option value={2}>2 spaces</option><option value={4}>4 spaces</option></select></label><p>Lexical SQL formatting preserves quoted text and comments. Checks quote and parenthesis balance; it does not validate database-specific SQL grammar.</p><Result {...result}/></DataShell>; }
export function XmlTool({ validate = false }: {
    validate?: boolean;
}) {
    const [input, setInput] = useState(''), [indent, setIndent] = useState(2), [mode, setMode] = useState('format');
    const result = useMemo(() => attempt(() => { if (!input.trim())
        return ''; if (validate) {
        xmlDocument(input);
        return 'Valid XML';
    } return mode === 'minify' ? minifyXml(input) : formatXml(input, indent); }), [input, indent, validate, mode]);
    return <DataShell><Actions example={() => setInput('<root><item id="1">Hello &amp; welcome</item><item>Two</item></root>')} clear={() => { setInput(''); setIndent(2); setMode('format'); }}/><TextInput label="XML input" value={input} onChange={setInput}/>{!validate && <><div role="tablist" aria-label="XML mode">{['format', 'minify'].map(m => <button key={m} role="tab" aria-selected={mode === m} onClick={() => setMode(m)} className="tb-v2-mode-tab">{m === 'format' ? 'Format' : 'Minify'}</button>)}</div><label>Indent<select aria-label="Indent" value={indent} onChange={e => setIndent(Number(e.target.value))}><option value={2}>2 spaces</option><option value={4}>4 spaces</option></select></label></>}<p>Checks well-formedness, not XSD or DTD validity. DTD declarations are unsupported. Minify removes whitespace between child elements; mixed text, CDATA and xml:space="preserve" are retained.</p><Result {...result}/></DataShell>;
}
export function JsxTool() { const [input, setInput] = useState(''); const result = useMemo(() => attempt(() => input.trim() ? htmlToJsx(input) : ''), [input]); return <DataShell><Actions example={() => setInput('<label for="name" class="field" style="color: red">Name<input id="name" disabled></label>')} clear={() => setInput('')}/><TextInput label="HTML input" value={input} onChange={setInput}/><p>Uses the browser HTML parser, including its repair of malformed markup. Inline handlers and executable embeds are rejected. Text is emitted as JSX string expressions.</p><Result {...result}/></DataShell>; }
export function DiffTool() { const [a, setA] = useState(''), [b, setB] = useState(''); const result = useMemo(() => attempt(() => diffLines(a, b)), [a, b]); return <DataShell><Actions example={() => { setA('const answer = 41;\nconsole.log(answer);'); setB('const answer = 42;\nconsole.log(answer);'); }} clear={() => { setA(''); setB(''); }}/><TextInput label="Original code" value={a} onChange={setA}/><TextInput label="Modified code" value={b} onChange={setB}/><Result {...result}/></DataShell>; }
