export const consolidatedAliases: Record<string, string> = {
  "markdown-table-from-json": "json-to-markdown-table",
  "image-to-base64": "base64-image-converter",
  "text-sorter": "text-line-sorter",
  "smart-text-sorter": "text-line-sorter",
  "serp-simulator": "serp-preview",
  "serp-snippet-preview": "serp-preview",
  "readability-score-calculator": "readability-score",
  "image-size-resizer": "image-resizer",
  "resize": "image-resizer",
  "spelling-checker": "grammar-checker",
  "favicon-png-maker": "favicon-generator",
  "favicon-icon-generator": "favicon-generator",
  "favicon-grabber": "batch-favicon-downloader",
  "json-path-evaluator": "json-path-tester",
  "json-to-typescript-interface": "json-to-typescript",
  "json-to-typescript-types": "json-to-typescript",
  "keyword-density-analyzer": "keyword-density-checker",
  "random-mac-generator": "mac-address-generator",
  "json-escape-unescape": "backslash-escape-unescape",
  "image-dimension-checker": "detect",
  "rotate": "image-rotate",
  "robots-txt-editor": "robots-txt-checker",
  "robots-txt-validator": "robots-txt-checker",
  "robots-txt-analyzer": "robots-txt-checker",
  "sitemap-extractor": "sitemap-analyzer",
  "word-density-analyzer": "word-frequency-table",
  "unlock-pdf": "pdf-password-remover",
  "jwt-tester": "jwt-token-tester",
  "word-combinations": "word-combinations-generator",

  "text-case-converter": "case-converter",
  "title-case-converter": "case-converter",
  "url-encoder": "url-encode",
  "regex-match-tester": "regex-tester",
  "regex-pattern-tester": "regex-tester",
  "random-password-generator": "password-generator",
  "markdown-preview": "markdown-to-html",
  "markdown-editor": "markdown-to-html",
  "lorem-ipsum-words": "lorem-ipsum-generator",
  "jwt-inspector": "jwt-decoder",
  "jwt-token-decoder": "jwt-decoder",
  "read-time-calculator": "reading-time-calculator",
  "reading-pace-calculator": "reading-time-calculator",
  "reading-time-estimator": "reading-time-calculator",
  "text-statistics-calculator": "text-statistics",
  "sla-uptime-calculator": "uptime-calculator",
  "general-unit-converter": "all-in-one-unit-converter"
};

export const categoricalAliases: Record<string, string> = {
  '/tools/images/image-to-base64': 'base64-image-converter',
  '/tools/images/image-size-resizer': 'image-resizer',
  '/tools/images/resize': 'image-resizer',
  '/tools/images/favicon-png-maker': 'favicon-generator',
  '/tools/images/favicon-icon-generator': 'favicon-generator',
  '/tools/images/favicon-grabber': 'batch-favicon-downloader',
  '/tools/images/image-dimension-checker': 'detect',
  '/tools/images/rotate': 'image-rotate',
  '/tools/pdf/unlock-pdf': 'pdf-password-remover',
};
