import { marked } from 'marked';
import { blogPosts, type BlogManifestEntry } from '@/content/blog-manifest';

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  date: string;
  category: string;
  tags: string[];
  author: string;
  readingTime: string;
  emoji: string;
  featuredImage?: string;
  content?: string;
}

// The manifest is statically generated by scripts/generate-blog-manifest.mjs,
// so Turbopack's NFT can trace all blog files without dynamic fs operations.

export function getBlogPosts(): BlogPost[] {
  return blogPosts.map((entry: BlogManifestEntry) => ({
    slug: entry.slug,
    title: entry.title,
    description: entry.description,
    date: entry.date,
    category: entry.category,
    tags: entry.tags,
    author: entry.author,
    readingTime: entry.readingTime,
    emoji: entry.emoji,
    featuredImage: entry.featuredImage ?? undefined,
  }));
}

export function getBlogPost(slug: string): BlogPost | null {
  const entry = blogPosts.find(
    (p: BlogManifestEntry) => p.slug === slug,
  );
  if (!entry) return null;

  return {
    slug: entry.slug,
    title: entry.title,
    description: entry.description,
    date: entry.date,
    category: entry.category,
    tags: entry.tags,
    author: entry.author,
    readingTime: entry.readingTime,
    emoji: entry.emoji,
    featuredImage: entry.featuredImage ?? undefined,
    content: marked(entry.content) as string,
  };
}
