import { Marked } from 'marked';
import { blogPosts, type BlogManifestEntry } from '@/content/blog-manifest';

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  date: string;
  category: string;
  tags: string[];
  author: string;
  readingTime: string;
  emoji: string;
  featuredImage?: string;
  content?: string;
}

// The article page renders the post title as the page's only <h1>, so a
// leading `# Title` line in the markdown body is dropped and any other h1
// is demoted to h2.
const blogMarked = new Marked({
  renderer: {
    heading({ tokens, depth }) {
      const level = Math.min(Math.max(depth, 2), 6);
      return `<h${level}>${this.parser.parseInline(tokens)}</h${level}>\n`;
    },
  },
});

export function renderBlogMarkdown(markdown: string): string {
  const body = markdown.replace(/^\s*# [^\n]*\n+/, '');
  return blogMarked.parse(body, { async: false });
}

// The manifest is statically generated by scripts/generate-blog-manifest.mjs,
// so Turbopack's NFT can trace all blog files without dynamic fs operations.

function resolveFeaturedImage(image: string | null | undefined): string | undefined {
  // Legacy generated covers should not depend on the external placeholder API.
  return /^https:\/\/api\.radtx\.com\/gradient\/[0-9a-f]{6}-[0-9a-f]{6}\/1200\/630$/.test(image ?? '')
    ? '/images/blog-placeholder.png'
    : image ?? undefined;
}

export function getBlogPosts(): BlogPost[] {
  return blogPosts.map((entry: BlogManifestEntry) => ({
    slug: entry.slug,
    title: entry.title,
    description: entry.description,
    date: entry.date,
    category: entry.category,
    tags: entry.tags,
    author: entry.author,
    readingTime: entry.readingTime,
    emoji: entry.emoji,
    featuredImage: resolveFeaturedImage(entry.featuredImage),
  }));
}

export function getBlogPost(slug: string): BlogPost | null {
  const entry = blogPosts.find(
    (p: BlogManifestEntry) => p.slug === slug,
  );
  if (!entry) return null;

  return {
    slug: entry.slug,
    title: entry.title,
    description: entry.description,
    date: entry.date,
    category: entry.category,
    tags: entry.tags,
    author: entry.author,
    readingTime: entry.readingTime,
    emoji: entry.emoji,
    featuredImage: resolveFeaturedImage(entry.featuredImage),
    content: renderBlogMarkdown(entry.content),
  };
}
