export interface EmojiEntry {
  char: string;
  name: string;
  keywords: string[];
}

// Curated set for the punycode tool's emoji picker - real emoji/symbol
// domains (▲.to, 😀.ws, etc.) exist and are a normal punycode test case, but
// most of these characters have no keyboard shortcut, so people need a way
// to browse/search for one instead of typing it. Not an exhaustive Unicode
// emoji database - just enough breadth per category to be genuinely useful,
// with keywords covering common search terms (including plain misspellings
// like "barrell" -> barrel).
export const EMOJI_DATA: EmojiEntry[] = [
  // Smileys & emotion
  { char: "😀", name: "grinning face", keywords: ["smile", "happy", "grin"] },
  { char: "😂", name: "face with tears of joy", keywords: ["laugh", "lol", "funny", "crying laughing"] },
  { char: "😍", name: "heart eyes", keywords: ["love", "crush", "smitten"] },
  { char: "😎", name: "smiling face with sunglasses", keywords: ["cool", "sunglasses", "shades"] },
  { char: "🥳", name: "partying face", keywords: ["party", "celebrate", "birthday"] },
  { char: "😭", name: "loudly crying face", keywords: ["cry", "sad", "tears"] },
  { char: "😡", name: "angry face", keywords: ["mad", "rage", "furious"] },
  { char: "😴", name: "sleeping face", keywords: ["sleep", "tired", "zzz"] },
  { char: "🤔", name: "thinking face", keywords: ["think", "hmm", "ponder"] },
  { char: "😇", name: "smiling face with halo", keywords: ["angel", "innocent", "halo"] },
  { char: "🤯", name: "exploding head", keywords: ["mind blown", "shocked", "wow"] },
  { char: "🥺", name: "pleading face", keywords: ["puppy eyes", "please", "beg"] },

  // Hearts & love
  { char: "❤️", name: "red heart", keywords: ["love", "heart"] },
  { char: "🧡", name: "orange heart", keywords: ["love", "heart"] },
  { char: "💛", name: "yellow heart", keywords: ["love", "heart"] },
  { char: "💚", name: "green heart", keywords: ["love", "heart"] },
  { char: "💙", name: "blue heart", keywords: ["love", "heart"] },
  { char: "💜", name: "purple heart", keywords: ["love", "heart"] },
  { char: "🖤", name: "black heart", keywords: ["love", "heart", "goth"] },
  { char: "💔", name: "broken heart", keywords: ["heartbreak", "sad", "breakup"] },
  { char: "💕", name: "two hearts", keywords: ["love", "hearts"] },
  { char: "💖", name: "sparkling heart", keywords: ["love", "heart", "sparkle"] },

  // People & body
  { char: "👍", name: "thumbs up", keywords: ["like", "approve", "yes", "good"] },
  { char: "👎", name: "thumbs down", keywords: ["dislike", "no", "bad"] },
  { char: "👏", name: "clapping hands", keywords: ["applause", "clap", "bravo"] },
  { char: "🙌", name: "raising hands", keywords: ["celebrate", "hooray", "praise"] },
  { char: "🤝", name: "handshake", keywords: ["deal", "agreement", "shake"] },
  { char: "✌️", name: "victory hand", keywords: ["peace", "victory"] },
  { char: "🤘", name: "sign of the horns", keywords: ["rock", "metal"] },
  { char: "👀", name: "eyes", keywords: ["look", "watching", "see"] },
  { char: "🧠", name: "brain", keywords: ["mind", "smart", "think"] },
  { char: "💪", name: "flexed biceps", keywords: ["strong", "muscle", "gym"] },

  // Animals & nature
  { char: "🐱", name: "cat face", keywords: ["cat", "kitten", "meow"] },
  { char: "🐶", name: "dog face", keywords: ["dog", "puppy", "woof"] },
  { char: "🦊", name: "fox", keywords: ["fox"] },
  { char: "🐻", name: "bear", keywords: ["bear"] },
  { char: "🐼", name: "panda", keywords: ["panda"] },
  { char: "🐨", name: "koala", keywords: ["koala"] },
  { char: "🦁", name: "lion", keywords: ["lion"] },
  { char: "🐸", name: "frog", keywords: ["frog"] },
  { char: "🐧", name: "penguin", keywords: ["penguin"] },
  { char: "🦄", name: "unicorn", keywords: ["unicorn", "magic"] },
  { char: "🐝", name: "bee", keywords: ["bee", "insect"] },
  { char: "🦋", name: "butterfly", keywords: ["butterfly"] },
  { char: "🐢", name: "turtle", keywords: ["turtle", "slow"] },
  { char: "🐙", name: "octopus", keywords: ["octopus"] },
  { char: "🐬", name: "dolphin", keywords: ["dolphin"] },
  { char: "🌸", name: "cherry blossom", keywords: ["flower", "blossom", "spring"] },
  { char: "🌻", name: "sunflower", keywords: ["flower", "sunflower"] },
  { char: "🌵", name: "cactus", keywords: ["cactus", "plant", "desert"] },
  { char: "🌲", name: "evergreen tree", keywords: ["tree", "forest", "pine"] },
  { char: "🍀", name: "four leaf clover", keywords: ["clover", "lucky", "luck"] },

  // Food & drink
  { char: "🍕", name: "pizza", keywords: ["pizza", "food"] },
  { char: "🍔", name: "hamburger", keywords: ["burger", "food"] },
  { char: "🌮", name: "taco", keywords: ["taco", "food"] },
  { char: "🍣", name: "sushi", keywords: ["sushi", "food"] },
  { char: "🍩", name: "doughnut", keywords: ["donut", "doughnut", "food"] },
  { char: "🍦", name: "soft ice cream", keywords: ["ice cream", "dessert"] },
  { char: "🍰", name: "shortcake", keywords: ["cake", "dessert"] },
  { char: "🎂", name: "birthday cake", keywords: ["cake", "birthday"] },
  { char: "☕", name: "hot beverage", keywords: ["coffee", "tea", "drink"] },
  { char: "🍺", name: "beer mug", keywords: ["beer", "drink"] },
  { char: "🍷", name: "wine glass", keywords: ["wine", "drink"] },
  { char: "🍎", name: "red apple", keywords: ["apple", "fruit"] },
  { char: "🍌", name: "banana", keywords: ["banana", "fruit"] },
  { char: "🥑", name: "avocado", keywords: ["avocado", "fruit"] },
  { char: "🛢️", name: "oil drum", keywords: ["barrel", "drum", "oil"] },

  // Travel & places
  { char: "🚀", name: "rocket", keywords: ["rocket", "space", "launch"] },
  { char: "✈️", name: "airplane", keywords: ["plane", "flight", "travel"] },
  { char: "🚗", name: "car", keywords: ["car", "drive"] },
  { char: "🚲", name: "bicycle", keywords: ["bike", "bicycle"] },
  { char: "⛵", name: "sailboat", keywords: ["boat", "sail"] },
  { char: "🏝️", name: "desert island", keywords: ["island", "beach", "vacation"] },
  { char: "🏔️", name: "snow capped mountain", keywords: ["mountain", "snow"] },
  { char: "🌋", name: "volcano", keywords: ["volcano"] },
  { char: "🗽", name: "statue of liberty", keywords: ["liberty", "new york", "usa"] },
  { char: "🗼", name: "tokyo tower", keywords: ["tower", "tokyo", "japan"] },
  { char: "🏠", name: "house", keywords: ["home", "house"] },
  { char: "🏢", name: "office building", keywords: ["building", "office"] },
  { char: "🌍", name: "globe showing Europe-Africa", keywords: ["earth", "world", "globe"] },
  { char: "🌎", name: "globe showing Americas", keywords: ["earth", "world", "globe"] },
  { char: "🌏", name: "globe showing Asia-Australia", keywords: ["earth", "world", "globe"] },
  { char: "🌙", name: "crescent moon", keywords: ["moon", "night"] },
  { char: "☀️", name: "sun", keywords: ["sun", "sunny"] },
  { char: "⭐", name: "star", keywords: ["star"] },
  { char: "🌈", name: "rainbow", keywords: ["rainbow", "pride"] },
  { char: "🔥", name: "fire", keywords: ["fire", "flame", "lit", "hot"] },
  { char: "⚡", name: "high voltage", keywords: ["lightning", "bolt", "electric"] },
  { char: "❄️", name: "snowflake", keywords: ["snow", "cold", "winter"] },

  // Activities & objects
  { char: "⚽", name: "soccer ball", keywords: ["soccer", "football", "ball"] },
  { char: "🏀", name: "basketball", keywords: ["basketball", "ball"] },
  { char: "🎮", name: "video game controller", keywords: ["gaming", "game", "controller"] },
  { char: "🎸", name: "guitar", keywords: ["guitar", "music"] },
  { char: "🎧", name: "headphones", keywords: ["music", "headphones", "audio"] },
  { char: "🎨", name: "artist palette", keywords: ["art", "paint", "palette"] },
  { char: "📷", name: "camera", keywords: ["camera", "photo"] },
  { char: "🎬", name: "clapper board", keywords: ["movie", "film", "clapper"] },
  { char: "📚", name: "books", keywords: ["books", "read", "library"] },
  { char: "✏️", name: "pencil", keywords: ["pencil", "write"] },
  { char: "💻", name: "laptop", keywords: ["laptop", "computer"] },
  { char: "📱", name: "mobile phone", keywords: ["phone", "mobile"] },
  { char: "💡", name: "light bulb", keywords: ["idea", "light", "bulb"] },
  { char: "🔑", name: "key", keywords: ["key", "unlock"] },
  { char: "🔒", name: "locked", keywords: ["lock", "secure", "private"] },
  { char: "🎁", name: "wrapped gift", keywords: ["gift", "present"] },
  { char: "💰", name: "money bag", keywords: ["money", "cash", "rich"] },
  { char: "💎", name: "gem stone", keywords: ["diamond", "gem", "jewel"] },
  { char: "🏆", name: "trophy", keywords: ["trophy", "win", "award"] },
  { char: "🎯", name: "direct hit", keywords: ["target", "goal", "dart"] },
  { char: "🔔", name: "bell", keywords: ["bell", "notification", "alert"] },
  { char: "📌", name: "pushpin", keywords: ["pin", "location", "map"] },
  { char: "🧩", name: "puzzle piece", keywords: ["puzzle", "piece"] },
  { char: "🎈", name: "balloon", keywords: ["balloon", "party"] },
  { char: "🎉", name: "party popper", keywords: ["party", "celebrate", "confetti"] },

  // Symbols & shapes (closer in spirit to real registered symbol domains)
  { char: "▲", name: "black up-pointing triangle", keywords: ["triangle", "arrow up"] },
  { char: "★", name: "black star", keywords: ["star"] },
  { char: "♥", name: "heart suit", keywords: ["heart", "card suit"] },
  { char: "♦", name: "diamond suit", keywords: ["diamond", "card suit"] },
  { char: "☂", name: "umbrella", keywords: ["umbrella", "rain"] },
  { char: "☮", name: "peace symbol", keywords: ["peace"] },
  { char: "☯", name: "yin yang", keywords: ["balance", "yin yang"] },
  { char: "✓", name: "check mark", keywords: ["check", "yes", "done", "tick"] },
  { char: "✗", name: "ballot x", keywords: ["cross", "no", "wrong", "x mark"] },
  { char: "∞", name: "infinity", keywords: ["infinity", "forever"] },
  { char: "☘", name: "shamrock", keywords: ["clover", "lucky", "irish"] },
  { char: "❄", name: "snowflake symbol", keywords: ["snow", "cold", "winter"] },
  { char: "⚓", name: "anchor", keywords: ["anchor", "boat", "nautical"] },
  { char: "⚔", name: "crossed swords", keywords: ["sword", "battle", "fight"] },

  // Flags (already showcased as .ws-style flag-emoji domains in the wild)
  { char: "🏳️", name: "white flag", keywords: ["flag", "surrender", "white"] },
  { char: "🏴", name: "black flag", keywords: ["flag", "black", "pirate"] },
  { char: "🏁", name: "checkered flag", keywords: ["flag", "finish", "race"] },
  { char: "🏳️‍🌈", name: "rainbow flag", keywords: ["pride", "flag", "rainbow"] },
];
