// Rewritten content for 10 tools flagged for quality issues.
// Not wired into the app yet - staged for review before merging into data/tool-content.ts.

export interface FixBatchExample {
  title: string;
  code: string;
  note?: string;
}

export interface FixBatchEntry {
  description: string;
  examples: FixBatchExample[];
}

const FIX_BATCH_97: Record<string, FixBatchEntry> = {
  cutter: {
    description: `Removing the first thirty seconds of dead air from a two-hour recording shouldn't take anywhere near as long as the recording itself, and it doesn't have to, since a cut made at the file's existing keyframes copies the kept footage directly rather than decoding and rebuilding the whole thing, so export time stays roughly the same whether the final clip is five minutes or ninety, rather than scaling with how much footage gets kept. This tool cuts and trims video files by copying footage directly from existing keyframes instead of re-encoding, keeping export time fast and largely independent of the result's length. Useful for trimming a long recording down to a short highlight without an export that scales with the original length, removing dead air from a stream recording in seconds, or cutting a large file down to its relevant section quickly regardless of how much ends up being kept.`,
    examples: [
      {
        title: 'Trim dead air from a stream recording',
        code: `Input: stream-vod.mp4 (2h), remove: 0:00-0:30\nOutput: stream-vod-trimmed.mp4 (exported in seconds)`,
        note: 'Export time stays fast regardless of the original length.',
      },
      {
        title: 'Cut a highlight without a length-proportional wait',
        code: `Input: full-lecture.mp4 (90 min), keep: 12:00-17:00\nOutput: highlight.mp4 (5 min, exported almost instantly)`,
        note: 'Copies footage directly instead of re-encoding the full duration.',
      },
    ],
  },

  'db-query-formatter': {
    description: `A query pulled straight from a database's slow-query log or an ORM's debug trace usually shows up as one dense, unreadable line, generated by application code rather than typed by a person, which is a genuinely different starting point than a query already being hand-written in an editor with at least some formatting applied as it goes. This tool formats and prettifies SQL queries with keyword highlighting and indentation, built around turning a raw, machine-generated query string into something readable for actual debugging. Useful for formatting a query copied straight out of a slow-query log to actually understand what it's doing, cleaning up an ORM's auto-generated SQL trace before diagnosing a performance issue, or making a dense, single-line query readable enough to spot the actual problem in it.`,
    examples: [
      {
        title: 'Format a query pulled from a slow-query log',
        code: `Input: SELECT u.id,u.name,o.total FROM users u JOIN orders o ON u.id=o.user_id WHERE o.total>100\nOutput:\nSELECT u.id, u.name, o.total\nFROM users u\nJOIN orders o ON u.id = o.user_id\nWHERE o.total > 100`,
        note: 'Turns a dense, machine-generated line into a readable query.',
      },
      {
        title: "Clean up an ORM's debug trace",
        code: `Input: [single-line auto-generated SQL from an ORM trace]\nOutput: properly indented query with keywords highlighted`,
        note: 'Makes application-generated SQL readable for debugging.',
      },
    ],
  },

  detect: {
    description: `A file renamed from .png to .jpg doesn't actually become a JPEG just because the extension changed, the real format lives in the file's own binary signature at the very start of its content, and software that trusts the extension rather than checking that signature is exactly how a mismatched file ends up throwing a confusing, unhelpful "can't open this file" error. This tool detects an image's actual format by reading its binary signature directly, along with its real dimensions, size, and color depth, rather than trusting whatever the file extension happens to claim. Useful for figuring out a file's true format when its extension doesn't seem to match how it actually behaves, catching a mismatched extension before it causes an unexplained error somewhere else, or checking an image's actual color depth and dimensions without opening it in a full editor first.`,
    examples: [
      {
        title: 'Catch a mismatched file extension',
        code: `Input: photo.jpg (actual binary signature: PNG)\nOutput: format: PNG (extension claims JPEG, mismatch detected)`,
        note: 'Reads the actual file content rather than trusting the extension.',
      },
      {
        title: 'Check color depth without opening an editor',
        code: `Input: graphic.png\nOutput: 1920x1080, 24-bit color depth, 340 KB`,
        note: 'Surfaces real file details directly.',
      },
    ],
  },

  'discount-calculator': {
    description: `Thirty percent off followed by an extra ten percent at checkout doesn't add up to forty percent off total, since that second discount applies to the already-discounted price rather than the original one, which means the two together actually work out closer to thirty-seven percent, a compounding effect that's easy to miscalculate by simply adding the percentages together. This tool calculates sale prices and savings, including stacked discounts applied one after another correctly rather than added together as if they were a single flat percentage. Useful for figuring out the real total discount when a sale percentage and an extra checkout coupon stack together, checking that a store's advertised combined discount actually matches what compounding percentages would produce, or calculating exactly how much a multi-discount purchase actually saves rather than estimating it by simple addition.`,
    examples: [
      {
        title: 'Calculate a stacked discount correctly',
        code: `Input: $100, 30% off, then extra 10% off\nOutput: $100 -> $70 -> $63 (37% total discount, not 40%)`,
        note: 'Applies the second discount to the already-reduced price.',
      },
      {
        title: "Check a store's advertised combined discount",
        code: `Input: "40% off" claimed for 30% + 10% stacked\nOutput: actual combined discount: 37%`,
        note: 'Verifies compounding math against a simple-addition claim.',
      },
    ],
  },

  'dns-lookup-tool': {
    description: `Troubleshooting why a domain's DNS changes haven't propagated after switching providers usually comes down to checking NS records specifically, which nameservers are actually authoritative for a domain right now, a detail that matters during a delegation change in a way A or MX records simply don't address. This tool checks A, MX, CNAME, TXT, and NS records for any domain, built around the record types that matter for diagnosing DNS delegation and infrastructure issues specifically. Useful for confirming which nameservers are actually authoritative for a domain after a provider switch, checking whether an NS record change has actually propagated yet, or looking up a domain's core infrastructure records during a DNS migration.`,
    examples: [
      {
        title: 'Confirm authoritative nameservers after a switch',
        code: `Input: example.com\nOutput: NS records: ns1.newprovider.com, ns2.newprovider.com`,
        note: 'Shows exactly which nameservers are currently authoritative.',
      },
      {
        title: 'Check core infrastructure records during a migration',
        code: `Input: example.com\nOutput: A, MX, CNAME, TXT, and NS records listed together`,
        note: 'Covers the record types relevant to delegation troubleshooting.',
      },
    ],
  },

  'dns-lookup-v2': {
    description: `A domain resolving correctly over legacy IPv4 says nothing about whether it also resolves over IPv6, and checking that specifically means looking up an AAAA record, a detail that's easy to overlook entirely if a lookup tool only ever checks the older record types most domains have carried for decades. This tool queries A, AAAA, MX, TXT, and CNAME records for any domain, including IPv6 addressing alongside the more traditional record types. Useful for confirming a domain actually resolves correctly over IPv6, not just legacy IPv4, checking whether a newly added AAAA record has propagated, or auditing a domain's records with modern IPv6 addressing included rather than assumed.`,
    examples: [
      {
        title: 'Confirm IPv6 resolution',
        code: `Input: example.com\nOutput: AAAA record: 2606:4700:4700::1111`,
        note: 'Checks IPv6 addressing that older lookups often skip.',
      },
      {
        title: 'Check whether a new AAAA record has propagated',
        code: `Input: example.com\nOutput: AAAA record found (added within the last hour)`,
        note: 'Confirms an IPv6 record change has actually taken effect.',
      },
    ],
  },

  'dominant-color-extractor': {
    description: `Asking what color an image actually is, the single hue that defines its overall mood or backbone, is a different question from wanting a usable design palette pulled from it, and answering it means ranking colors by how much of the image's actual pixel area each one covers, not just listing which colors happen to be present somewhere in the frame. This tool extracts an image's dominant colors ranked by actual pixel coverage, surfacing which single color genuinely defines the image rather than an unordered palette. Useful for finding the one color that most defines a photo's overall mood at a glance, ranking colors by how much of an image they actually cover rather than just listing what's present, or identifying an image's backbone color for a quick visual summary rather than a full design palette.`,
    examples: [
      {
        title: "Find a photo's single defining color",
        code: `Input: sunset-photo.jpg\nOutput: #E8734A covers 34% of the image (most dominant)`,
        note: 'Ranks by actual pixel coverage rather than just listing colors present.',
      },
      {
        title: 'Rank colors by coverage',
        code: `Input: product-photo.jpg\nOutput: #F5F5F0 (52%), #2A2A2A (28%), #C9A876 (12%)`,
        note: 'Orders colors from most to least of the actual image area.',
      },
    ],
  },

  'dpi-ppi-calculator': {
    description: `Whether a specific image will print sharp at a given size and how densely packed the pixels are on an actual physical screen are two different questions answered by the same underlying math, one asking whether a file has enough resolution for a print job, the other describing a display device's own specification, like why a phone advertised as "retina" packs noticeably more pixels per inch than an older, lower-density screen. This tool calculates dots per inch and pixels per inch for both print sizing and screen resolution, covering a display's own pixel density alongside whether a specific image file will hold up at a given print size. Useful for calculating a monitor or phone screen's actual pixel density from its resolution and physical size, checking whether an image has enough resolution for a specific print size, or comparing two screens' pixel density specifications directly.`,
    examples: [
      {
        title: "Calculate a phone screen's actual pixel density",
        code: `Input: 6.1 in screen, 2556x1179 resolution\nOutput: approximately 460 PPI`,
        note: "Describes a display device's own specification, not a print check.",
      },
      {
        title: 'Check if an image has enough resolution to print',
        code: `Input: 3000x2000px image, print size: 8x10 in\nOutput: 300 DPI (meets standard print quality threshold)`,
        note: 'Confirms a specific file holds up at a specific print size.',
      },
    ],
  },

  'edit-pdf': {
    description: `Adding a note, label, or replacement graphic to a PDF often means opening a full editor just to place one small overlay, while the original document content should remain available underneath for review. This tool adds text and image overlays to PDF pages in your browser without replacing the existing PDF text or images. Useful for adding a visible label to a finished report, placing a logo or signature image on a form, or adding a note to a PDF while keeping its original content intact.`,
    examples: [
      {
        title: 'Add a review note to a finalized PDF',
        code: `Input: contract.pdf, text overlay: "Check clause 4" on page 3\nOutput: contract-edited.pdf`,
        note: 'Adds a visible note while leaving the original wording underneath.',
      },
      {
        title: 'Place a new logo on a finished PDF',
        code: `Input: brochure.pdf, image overlay: new-logo.png on page 1\nOutput: brochure-updated.pdf`,
        note: 'Places a replacement graphic without needing the original source file.',
      },
    ],
  },

  'email-generator': {
    description: `Test accounts scattered across a dozen different fake domains are hard to filter or bulk-delete later, and there's a real risk a typo sends an actual email to someone's real inbox by accident, both problems a set of test addresses sharing one consistent, obviously-fake domain avoids entirely by design. This tool generates realistic-looking email addresses under a custom domain specifically chosen for testing, rather than generating one field among several unrelated data types. Useful for creating a batch of test accounts that all share one recognizable domain for easy filtering later, generating email addresses under a domain that's obviously fake so a bug can never send real mail to a real inbox, or producing realistic-looking test emails for a signup flow without touching any other kind of fake data.`,
    examples: [
      {
        title: 'Generate test accounts under one filterable domain',
        code: `Input: domain: test.example-qa.com, count: 20\nOutput: user1@test.example-qa.com ... user20@test.example-qa.com`,
        note: 'Keeps every test address under one recognizable, easy-to-filter domain.',
      },
      {
        title: 'Avoid accidentally emailing a real inbox',
        code: `Input: domain: fakemail.invalid\nOutput: jane.doe@fakemail.invalid`,
        note: 'Uses an obviously fake domain so a bug can never reach a real person.',
      },
    ],
  },
};

export default FIX_BATCH_97;
