import { schemaReview, notebookCleanerReview, notebookImageReview, sqlReview } from '../regressions/data-review.mjs';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
const out = tool => tool.getByLabel('Output', { exact: true });
const input = tool => tool.getByLabel('JSON input', { exact: true });
async function reset({tool,expect,check}, label='JSON input') {
  await tool.locator('button.tb-v2-tool-text-action').filter({hasText:/^Clear$/}).click();
  await expect(tool.getByLabel(label,{exact:true})).toHaveValue('');
  await expect(tool.getByRole('alert')).toHaveCount(0);
  if(await out(tool).count()) { const text=(await out(tool).textContent()).trim(); check(text===''||text==='-', 'Clear removes the previous output.'); }
  check(true, 'Clear resets input and errors.');
}
async function invalid(ctx,label='JSON input',value='{"bad":}') {
  await ctx.tool.getByLabel(label,{exact:true}).fill(value);
  await ctx.expect(ctx.tool.getByRole('alert')).toBeVisible();
  if(await out(ctx.tool).count()) await ctx.expect(out(ctx.tool)).toHaveText('');
  ctx.check(true,'Invalid input produces a visible error and removes stale output.');
}
async function example(ctx,label='JSON input') {
  await ctx.tool.getByRole('button',{name:/^Examples?$/}).click();
  await ctx.expect(ctx.tool.getByLabel(label,{exact:true})).not.toHaveValue('');
}
async function saveDownload(ctx, button, filename) {
 const [download]=await Promise.all([ctx.page.waitForEvent('download'),ctx.tool.getByRole('button',{name:button,exact:true}).click()]);const path=join(ctx.artifactsDir,filename);await download.saveAs(path);return readFile(path);
}
const cases=[];
async function waitForActions(ctx) {
  // Framework scripts can arrive before the tool's React handlers are attached.
  await ctx.expect.poll(() => ctx.tool.getByRole('button', {name:/^Examples?$/}).evaluate(button =>
    Object.keys(button).some(key => key.startsWith('__reactProps$') && typeof button[key]?.onClick === 'function')
  ), {timeout: 30_000, message: 'Examples has a hydrated React click handler'}).toBe(true);
}
function add(slugs,test){for(const slug of slugs) cases.push({slug,requiresExample:true,requiresClear:true,test:async ctx=>{await waitForActions(ctx);await test(ctx);const review = slug === 'json-schema-validator' ? schemaReview : slug === 'jupyter-cleaner' ? notebookCleanerReview : slug === 'notebook-to-html' ? notebookImageReview : ['sql-formatter','sql-prettifier','db-query-formatter'].includes(slug) ? sqlReview : null;if(review) await review(ctx);}});}
add(['json-to-python'],async ctx=>{const{tool,expect,check}=ctx;await example(ctx);await input(tool).fill('{"a":[true,null,2]}');await expect(out(tool)).toHaveText('data = {\n    "a": [\n        True,\n        None,\n        2\n    ]\n}');check(true,'Python output has quoted keys, literal nested values and one assignment.');await invalid(ctx);await reset(ctx);});
add(['json-to-typescript','json-to-typescript-interface','json-to-typescript-types'],async ctx=>{const{tool,expect,check}=ctx;await example(ctx);await input(tool).fill('{"a":[1,"x",null]}');await expect(out(tool)).toHaveText('interface Root {\n  a: (number | string | null)[];\n}\n');check(true,'TypeScript array union is parenthesized and retains [].');await tool.getByLabel('Root type name',{exact:true}).fill('class');await expect(tool.getByRole('alert')).toContainText('identifiers');await tool.getByLabel('Root type name',{exact:true}).fill('Root');await input(tool).fill('{}');await expect(out(tool)).toHaveText('type Root = Record<string, never>;\n');await invalid(ctx);await reset(ctx);});
add(['json-path-tester','json-path-evaluator'],async ctx=>{const{tool,expect,check}=ctx;await example(ctx);await expect(out(tool)).toHaveText('[\n  "One",\n  "Two"\n]');await tool.getByLabel('JSONPath expression',{exact:true}).fill('$..book[?(@.price > 20)].title');await expect(out(tool)).toHaveText('[\n  "Two"\n]');await tool.getByLabel('JSONPath expression',{exact:true}).fill('$.missing');await expect(out(tool)).toHaveText('[]');await tool.getByLabel('JSONPath expression',{exact:true}).fill('$[?(@.x == alert(1))]');await expect(tool.getByRole('alert')).toBeVisible();check(true,'Wildcard projection, recursive comparison and no-match results are exact; executable expressions rejected.');await reset(ctx);});
add(['json-schema-validator'],async ctx=>{const{tool,expect,check}=ctx;await example(ctx);await expect(out(tool)).toHaveText('Valid against the supported schema.');await tool.getByLabel('JSON schema',{exact:true}).fill('{"type":"integer"}');await input(tool).fill('2.5');await expect(tool.getByRole('alert')).toContainText('Expected integer');await input(tool).fill('null');await expect(tool.getByRole('alert')).toContainText('Expected integer');await tool.getByLabel('JSON schema',{exact:true}).fill('{"const":false}');await input(tool).fill('true');await expect(tool.getByRole('alert')).toContainText('const');await tool.getByLabel('JSON schema',{exact:true}).fill('{"$ref":"#"}');await expect(tool.getByRole('alert')).toContainText('Unsupported schema keyword');check(true,'Wrong types, null mismatch, falsy const and unsupported schema keywords fail visibly.');await reset(ctx);await expect(tool.getByLabel('JSON schema',{exact:true})).toHaveValue('');});
add(['sql-formatter','sql-prettifier','db-query-formatter'],async ctx=>{const{tool,expect,check}=ctx;await example(ctx,'SQL input');await expect(out(tool)).toHaveText("SELECT id, 'from  here' AS label\nFROM users\nWHERE active = 1;");await tool.getByLabel('SQL input',{exact:true}).fill("select 'it''s where', $$from  x$$ from t -- leave where\nwhere n != 2");await expect(out(tool)).toContainText("'it''s where'");await expect(out(tool)).toContainText('$$from  x$$');await expect(out(tool)).toContainText('-- leave where\nWHERE n != 2');await tool.getByLabel('Uppercase keywords').uncheck();await expect(out(tool)).toContainText('select');check(true,'SQL formatting preserves literal whitespace, escaped quotes, comments, dollar strings and !=.');await invalid(ctx,'SQL input',"select 'unterminated");await reset(ctx,'SQL input');});
add(['xml-formatter'],async ctx=>{const{tool,expect,check}=ctx;await example(ctx,'XML input');await tool.getByLabel('XML input',{exact:true}).fill('<root><child>value</child></root>');await expect(out(tool)).toHaveText('<root>\n  <child>value</child>\n</root>');await tool.getByLabel('XML input',{exact:true}).fill('<p>Hello <b>world</b>!<!--keep--><![CDATA[<x>]]></p>');await expect(out(tool)).toHaveText('<p>Hello <b>world</b>!<!--keep--><![CDATA[<x>]]></p>');check(true,'Single-child markup, mixed text, comments and CDATA are retained exactly.');await tool.getByRole('tab',{name:'Minify',exact:true}).click();await tool.getByLabel('XML input',{exact:true}).fill('<root>\n  <child>value</child>\n</root>');await expect(out(tool)).toHaveText('<root><child>value</child></root>');await invalid(ctx,'XML input','<root><a></root>');await reset(ctx,'XML input');});
add(['xml-validator'],async ctx=>{const{tool,expect,check}=ctx;await example(ctx,'XML input');await expect(out(tool)).toHaveText('Valid XML');await invalid(ctx,'XML input','<root><child></root>');check(true,'Valid XML accepted; mismatched closing tags rejected.');await reset(ctx,'XML input');});
add(['html-to-jsx'],async ctx=>{const{tool,expect,check}=ctx;await example(ctx,'HTML input');await tool.getByLabel('HTML input',{exact:true}).fill('<label for="x" class="a" style="color: red">Hi<input disabled></label>');await expect(out(tool)).toHaveText('<><label htmlFor={"x"} className={"a"} style={{"color":"red"}}>{"Hi"}<input disabled={true} /></label></>');await tool.getByLabel('HTML input',{exact:true}).fill('<p>{x} &amp; text</p>');await expect(out(tool)).toHaveText('<><p>{"{x} & text"}</p></>');check(true,'DOM conversion creates valid JSX attributes, style object, void tags and literal braces.');await invalid(ctx,'HTML input','<button onclick="alert(1)">go</button>');await reset(ctx,'HTML input');});
add(['code-diff'],async ctx=>{const{tool,expect,check}=ctx;await example(ctx,'Original code');await tool.getByLabel('Original code',{exact:true}).fill('a\nc');await tool.getByLabel('Modified code',{exact:true}).fill('a\nb\nc');await expect(out(tool)).toHaveText('  a\n+ b\n  c');check(true,'Insertion retains surrounding context without false removals.');await tool.getByLabel('Original code',{exact:true}).fill('a\n'.repeat(1100));await tool.getByLabel('Modified code',{exact:true}).fill('b\n'.repeat(1100));await expect(tool.getByRole('alert')).toContainText('limited');await reset(ctx,'Original code');await expect(tool.getByLabel('Modified code',{exact:true})).toHaveValue('');});
add(['json-formatter'],async ctx=>{const{tool,expect,check}=ctx;await example(ctx);await input(tool).fill('{"x":[1,true,null]}');await expect(out(tool)).toHaveText('{\n  "x": [\n    1,\n    true,\n    null\n  ]\n}');await tool.getByRole('tab',{name:'Minify',exact:true}).click();await expect(out(tool)).toHaveText('{"x":[1,true,null]}');check(true,'Formatted and minified JSON preserve nested values.');await input(tool).fill('{bad');await expect(tool.getByRole('alert')).toBeVisible();await reset(ctx);});
add(['json-validator'],async ctx=>{const{tool,expect,check}=ctx;await example(ctx);await input(tool).fill('null');await expect(tool.getByText('Valid JSON',{exact:true})).toBeVisible();await input(tool).fill('9007199254740993');await expect(tool.getByText('Valid JSON',{exact:true})).toBeVisible();await invalid(ctx);check(true,'JSON null and large valid numbers are syntactically valid; malformed object is rejected.');await reset(ctx);});
add(['json-editor'],async ctx=>{const{tool,expect,check}=ctx;await example(ctx,'JSON editor');await tool.getByLabel('JSON editor',{exact:true}).fill('{ "x": [1, true, null] }');await tool.getByRole('button',{name:'Minify',exact:true}).click();await expect(tool.getByLabel('JSON editor',{exact:true})).toHaveValue('{"x":[1,true,null]}');await tool.getByRole('button',{name:'Format',exact:true}).click();await expect(tool.getByLabel('JSON editor',{exact:true})).toHaveValue('{\n  "x": [\n    1,\n    true,\n    null\n  ]\n}');check(true,'Editor minify and format preserve data.');await invalid(ctx,'JSON editor');await reset(ctx,'JSON editor');});
add(['json-tree-view'],async ctx=>{const{tool,expect,check}=ctx;await example(ctx);await input(tool).fill('{"a":{"answer":42},"nil":null}');await tool.getByRole('button',{name:'Expand all',exact:true}).click();await expect(tool.getByText('42',{exact:true})).toBeVisible();await expect(tool.getByText('null',{exact:true})).toBeVisible();await tool.getByLabel('Search JSON tree').fill('missing');await expect(tool.getByText('No keys or values match "missing".')).toBeVisible();check(true,'Expanded nested number and null values are exact; search reports missing values.');await invalid(ctx);await reset(ctx);});
add(['json-graph-visualizer'],async ctx=>{const{tool,expect,check}=ctx;await example(ctx);await input(tool).fill('{"a":1,"b":null}');await expect(tool.getByText('Nodes',{exact:true}).locator('..').locator('p').first()).toHaveText('3');await expect(tool.getByText('Edges',{exact:true}).locator('..').locator('p').first()).toHaveText('2');await expect(tool.getByRole('img',{name:'JSON graph visualization'})).toBeVisible();check(true,'Object plus two primitives creates exactly three nodes and two edges, without duplicate primitive edges.');await invalid(ctx);await reset(ctx);});
add(['markdown-to-html','markdown-preview','markdown-editor','markdown-to-pdf'],async ctx=>{const{tool,expect,check}=ctx;await example(ctx,'Markdown input');await tool.getByLabel('Markdown input',{exact:true}).fill('# Hello\n\n**Bold** and `code`.');await expect(out(tool)).toHaveText('<h1>Hello</h1>\n<p><strong>Bold</strong> and <code>code</code>.</p>\n');await expect(tool.frameLocator('iframe[title="Rendered preview"]').getByRole('heading',{name:'Hello',exact:true})).toBeVisible();await tool.getByLabel('Markdown input',{exact:true}).fill('<script>alert(1)</script>\n\n[bad](javascript:alert(1))');await expect(out(tool)).not.toContainText('<script');await expect(out(tool)).not.toContainText('javascript:');check(true,'Markdown syntax produces exact HTML; executable tags and URLs are stripped.');if(await tool.getByRole('button',{name:'Download PDF',exact:true}).count()){await tool.getByLabel('Markdown input',{exact:true}).fill('# Hello\n\nAnswer 42.');const bytes=await saveDownload(ctx,'Download PDF','developer-data-markdown.pdf');check(bytes.subarray(0,5).toString()==='%PDF-','Download has a PDF signature.');const{PDFDocument}=await import('pdf-lib');const pdf=await PDFDocument.load(bytes);check(pdf.getPageCount()===1,'Generated PDF parses with one page.');check(bytes.toString('latin1').includes('(Answer 42.)'),'PDF contains the expected text, not just a blank page.');await tool.getByLabel('Markdown input',{exact:true}).fill('# বাংলা');await tool.getByRole('button',{name:'Download PDF',exact:true}).click();await expect(tool.getByRole('alert')).toContainText('Unicode');}await reset(ctx,'Markdown input');await expect(out(tool)).toHaveText('');});
const nb={nbformat:4,nbformat_minor:5,metadata:{custom:'keep'},cells:[{id:'intro',cell_type:'markdown',metadata:{},source:['# Hello']},{id:'code',cell_type:'code',metadata:{tags:['keep'],execution:{start:'old'}},execution_count:2,source:['print(42)'],outputs:[{output_type:'stream',name:'stdout',text:['42\n']}]}]};
add(['ipynb-formatter','jupyter-cleaner','notebook-to-html'],async ctx=>{const{tool,expect,check}=ctx;await example(ctx,'Notebook JSON input');await tool.getByLabel('Notebook JSON input',{exact:true}).fill(JSON.stringify(nb));const html=await tool.getByRole('button',{name:'Download HTML',exact:true}).count();if(html){await expect(tool.frameLocator('iframe[title="Notebook preview"]').getByRole('heading',{name:'Hello'})).toBeVisible();const bytes=await saveDownload(ctx,'Download HTML','developer-data-notebook.html');check(bytes.toString().includes('<pre>42\n</pre>')&&bytes.toString().includes('<code>print(42)</code>'),'Export contains exact source and saved stream output.');}else{const bytes=await saveDownload(ctx,'Download .ipynb','developer-data-notebook.ipynb');const result=JSON.parse(bytes.toString());const clean=await tool.getByText('Removes outputs, execution counts and execution UI metadata.',{exact:false}).count();check(result.cells[1].id==='code'&&result.cells[1].source[0]==='print(42)'&&(clean ? !('custom' in result.metadata) : result.metadata.custom==='keep'),'Notebook export preserves source and IDs; cleaner removes private metadata, formatter retains it.');if(clean){check(result.cells[1].outputs.length===0&&result.cells[1].execution_count===null,'Cleaner removes outputs and resets execution count.');check(!('execution' in result.cells[1].metadata)&&result.cells[1].metadata.tags[0]==='keep','Cleaner removes execution metadata but preserves tags.');}else{check(JSON.stringify(result)===JSON.stringify(nb),'Default formatting preserves notebook values and order.');await tool.getByLabel('Sort cells by execution count (changes document order)').check();const sorted=JSON.parse(await out(tool).textContent());check(sorted.cells[0].id==='code','Explicit sort puts executed code first.');}}await invalid(ctx,'Notebook JSON input','{"cells":[null]}');await reset(ctx,'Notebook JSON input');});
add(['csv-generator'],async ctx=>{const{tool,expect,check}=ctx;await tool.getByRole('button',{name:/^Examples?$/}).click();await tool.getByLabel('Row 1 column 1',{exact:true}).fill('Ada, "A"');const bytes=await saveDownload(ctx,'Download','developer-data-table.csv');check(bytes.toString()==='Name,Email,Role\r\n"Ada, ""A""",ada@example.com,Engineer\r\nGrace Hopper,grace@example.com,Admiral','CSV download quotes commas/double quotes and uses CRLF rows exactly.');await tool.locator('button.tb-v2-tool-text-action').filter({hasText:/^Clear$/}).click();await expect(tool.getByLabel('Column 1',{exact:true})).toHaveValue('');await expect(tool.getByRole('button',{name:'Download',exact:true})).toBeDisabled();check(true,'Clear removes rows and disables empty download.');});
export default cases;
