import { typescriptDownload } from '../regressions/misc-review.mjs';
import vm from 'node:vm';
import { load as yaml } from 'js-yaml';
const examples = tool => tool.getByRole('button',{name:'Examples',exact:true}).first().click();
const checkedPopulatedMobile = new WeakSet();
const clear = async tool => {
 const page=tool.page(),previous=page.viewportSize();
 await page.setViewportSize({width:320,height:800});
 const fits=await tool.evaluate(el=>{const box=el.getBoundingClientRect();return el.scrollWidth<=el.clientWidth+1&&box.left>=-1&&box.right<=innerWidth+1;});
 if(!fits)throw new Error('Populated result or error state overflows the 320px tool viewport');
 checkedPopulatedMobile.add(tool);
 await tool.getByRole('button',{name:'Clear',exact:true}).first().click();
 if(previous)await page.setViewportSize(previous);
};
const fill = (tool,label,value) => tool.getByLabel(label,{exact:true}).fill(value);
const pre = tool => tool.locator('pre').first();
const tests = {};
tests['cron-parser']=async({tool,expect,check})=>{
 await fill(tool,'Cron expression','0 9 * * 1-5');await expect(tool.locator('.tb-v2-cron-summary-text')).toContainText('9:00 AM');
 await expect(tool.locator('.tb-v2-cron-when').first()).toContainText('9:00 AM');const runs=await tool.locator('.tb-v2-cron-when').allTextContents();check([5,10].includes(runs.length)&&runs.every(t=>/^(Mon|Tue|Wed|Thu|Fri),/.test(t)),'All projected runs are weekdays at 09:00');
 await fill(tool,'Cron expression','1x * * * *');await expect(tool.getByRole('alert')).toContainText('Invalid minute');check(true,'Malformed numeric token rejected');await clear(tool);await expect(tool.locator('.tb-v2-cron-when')).toHaveCount(0);
};
tests['cron-generator']=async({tool,expect,check})=>{await examples(tool);await tool.getByLabel('Minute',{exact:true}).selectOption('15');await tool.getByLabel('Hour',{exact:true}).selectOption('12');await expect(tool.locator('.tb-v2-cron-when').first()).toContainText('12:15 PM');check((await tool.locator('.tb-v2-cron-when').allTextContents()).every(t=>t.includes('12:15 PM')),'Field builder schedules 12:15');await clear(tool);await expect(tool.locator('.tb-v2-cron-when')).toHaveCount(0);};
tests['regex-tester']=async({tool,expect,check})=>{
 await examples(tool);await fill(tool,'Regular expression pattern','(?<n>\\d+)');await fill(tool,'Test string','a12 b34');await expect(tool.locator('mark')).toHaveText(['12','34']);check((await tool.locator('.tb-v2-rgx-idx').allTextContents()).join(',')==='@1,@5','Exact regex match offsets 1 and 5');
 await tool.getByRole('button',{name:'g',exact:true}).click();await expect(tool.locator('mark')).toHaveText(['12']);check(true,'Non-global flag returns first match');await fill(tool,'Regular expression pattern','[');await expect(tool.getByRole('alert')).toContainText('Invalid');await clear(tool);await expect(tool.locator('mark')).toHaveCount(0);
};
tests['regex-explainer']=async({tool,expect,check})=>{await examples(tool);await expect(tool.locator('mark')).toHaveText(['12']);const tokens=await tool.locator('.tb-v2-rgx-list').first().innerText();check(tokens.includes('\\d')&&/digit/i.test(tokens),'Digit token explanation accompanies actual match');await clear(tool);await expect(tool.locator('mark')).toHaveCount(0);};
tests['regex-pattern-generator']=async({tool,expect,check})=>{await examples(tool);await tool.getByRole('button',{name:'IPv4 address',exact:true}).click();await fill(tool,'Test String','192.168.1.1');await expect(tool.locator('mark')).toHaveText(['192.168.1.1']);await fill(tool,'Test String','999.168.1.1');await expect(tool.locator('mark')).toHaveCount(0);const pattern=await pre(tool).textContent();check(new RegExp(pattern.slice(1,pattern.lastIndexOf('/'))).test('127.0.0.1')&&!new RegExp(pattern.slice(1,pattern.lastIndexOf('/'))).test('256.0.0.1'),'Generated IPv4 regex enforces octet limit');await clear(tool);};
tests['regex-pattern-builder']=async({tool,expect,check})=>{await examples(tool);await expect(tool.locator('mark')).toHaveText(['ada@example.com']);const code=await pre(tool).textContent();const re=new RegExp(code.slice(1,-1));check(re.test('ada@example.com')&&!re.test('not an email'),'Constructed regex accepts email example and rejects malformed input');await clear(tool);await expect(tool.locator('mark')).toHaveCount(0);};
tests['semver-checker']=async({tool,expect,check})=>{await fill(tool,'Version 1','1.0.0-alpha.2');await fill(tool,'Version 2','1.0.0-alpha.10');await expect(tool.locator('.tb-v2-tool-output-body')).toContainText('Smaller');await fill(tool,'Version 1','1.0.0');await expect(tool.locator('.tb-v2-tool-output-body')).toContainText('Greater');check(true,'Numeric prerelease order and release precedence');await fill(tool,'Version 1','01.0.0');await expect(tool.locator('.tb-v2-tool-output-body')).toContainText('Invalid');await clear(tool);await expect(tool.locator('.tb-v2-tool-output-body')).toHaveCount(0);};
tests['curl-to-python']=async({tool,expect,check})=>{await fill(tool,'cURL command',`curl https://example.com/users -d '{"active":true}'`);await expect(pre(tool)).toContainText('requests.request("POST", "https://example.com/users"');const code=await pre(tool).textContent();check(code.includes('data="{\\"active\\":true}"'),'Python body is a quoted string, not invalid Python JSON booleans');await fill(tool,'cURL command','curl --bad https://example.com');await expect(tool.getByRole('alert')).toContainText('Unsupported');await clear(tool);await expect(pre(tool)).toHaveText('');};
tests['curl-to-javascript']=async({tool,expect,check})=>{await fill(tool,'cURL command',`curl https://example.com/users -d '{"active":true}'`);await expect(pre(tool)).toContainText('"method": "POST"');const code=await pre(tool).textContent();let request;await vm.runInNewContext(`(async()=>{${code}})()`,{fetch:async(url,options)=>{request={url,options};return{status:200,text:async()=>''};},console:{log(){}}},{timeout:1000});check(request.url==='https://example.com/users'&&JSON.parse(request.options.body).active===true,'Generated JavaScript passes correct method, URL and exact body to fetch');await clear(tool);};
tests['js-minifier']=async({tool,expect,check})=>{await fill(tool,'JavaScript input','function add(a, b) { /* note */ return a + b; }');await tool.getByRole('button',{name:'Minify',exact:true}).click();await expect(pre(tool)).toContainText('function add',{timeout:20000});const output=await pre(tool).textContent();check(vm.runInNewContext(output+';add(2,3)',{},{timeout:1000})===5,'Minified JavaScript executes with result 5');await fill(tool,'JavaScript input','function {');await tool.getByRole('button',{name:'Minify',exact:true}).click();await expect(tool.getByRole('alert')).toBeVisible();await clear(tool);await expect(pre(tool)).toHaveText('');};
tests['css-minifier']=async({tool,expect,check})=>{await fill(tool,'CSS input','.a .b { /*x*/ width: calc(100% - 2px); content: "#ffffff"; }');await expect(pre(tool)).toHaveText('.a .b{width:calc(100% - 2px);content:"#ffffff";}');check(true,'Descendant selector, calc spaces and string literal preserved');await fill(tool,'CSS input','.a{');await expect(tool.getByRole('alert')).toBeVisible();await clear(tool);};
tests['html-minifier']=async({tool,expect,check})=>{const expected='<script>const x=1;</script><span>A</span> <span>B</span>';await fill(tool,'HTML input',expected+'<!--remove-->');await expect(pre(tool)).toHaveText(expected);check(true,'Closing script tag and inline word separator preserved');await clear(tool);};
tests['css-to-scss']=async({tool,expect,check})=>{const input=':root { --color: red; }\n.a { color: var(--color, blue); }';await fill(tool,'Input',input);await expect(pre(tool)).toHaveText(input);check(true,'Valid SCSS preserves runtime custom-property scope and fallback');await clear(tool);};
tests['css-to-tailwind']=async({tool,expect,check})=>{await fill(tool,'Input','display: flex; padding: 16px; gap: 8px;');await expect(pre(tool)).toHaveText('flex p-4 gap-2');check(true,'Known CSS maps to equivalent utility classes');await fill(tool,'Input','.a {');await expect(tool.getByRole('alert')).not.toHaveText('');await clear(tool);};
tests['css-to-styled-components']=async({tool,expect,check})=>{await fill(tool,'Input','.card { color: red; }');await expect(pre(tool)).toContainText('const Card = styled("div")');const output=await pre(tool).textContent();check(output.includes('color: red')&&output.includes('import styled'),'Generated named component retains declaration and import');await fill(tool,'Input','@media print {.a{color:red}}');await expect(tool.getByRole('alert')).toContainText('at-rules');await clear(tool);};
tests['css-validator']=async({tool,expect,check})=>{await fill(tool,'Input','.a { color: #fff; content: "}"; }');await expect(tool).toContainText('CSS syntax is valid');await fill(tool,'Input','.a { color red; }');await expect(tool).toContainText('CSS has');check(true,'Valid short hex/string brace accepted; missing colon rejected');await clear(tool);};
tests['html-validator']=async({tool,expect,check})=>{await fill(tool,'Input','<p>Hello</p>');await expect(tool).toContainText('HTML appears valid');await fill(tool,'Input','<div></span>');await expect(tool).toContainText('Mismatched closing tag');check(true,'Balanced fragment accepted and mismatched closing tag detected');await clear(tool);};
tests['html-live-preview']=async({tool,expect,check})=>{await fill(tool,'Html','<h1>Ada</h1><p>36</p>');await expect(tool.frameLocator('iframe').getByRole('heading',{name:'Ada'})).toBeVisible();check(await tool.locator('iframe').getAttribute('sandbox')==='','Preview renders markup in a restricted iframe');await clear(tool);await expect(tool.frameLocator('iframe').getByRole('heading')).toHaveCount(0);};
tests['html-table-generator']=async({tool,expect,check})=>{await fill(tool,'Table headers','Name,Age');await fill(tool,'CSV input','"Ada, A",36');await expect(tool.locator('table tbody tr').last()).toContainText('Ada, A');const code=await tool.getByLabel('HTML output',{exact:true}).inputValue();check(code.includes('<td>Ada, A</td>')&&code.includes('<td>36</td>'),'Quoted CSV comma stays in one table cell');await fill(tool,'CSV input','"unterminated');await expect(tool.getByRole('alert')).toContainText('Unclosed');await clear(tool);};
tests['api-spec-generator']=async({tool,expect,check})=>{await fill(tool,'Input',JSON.stringify({title:'API: example',endpoints:[{method:'GET',path:'/users'},{method:'POST',path:'/users'}],properties:{count:{type:'integer'}}}));await expect(pre(tool)).toContainText('openapi:');const doc=yaml(await pre(tool).textContent());check(doc.info.title==='API: example'&&Object.keys(doc.paths['/users']).length===2&&doc.components.schemas.Response.properties.count.type==='integer','OpenAPI YAML parses with two operations and integer schema');await fill(tool,'Input','{');await expect(tool.getByRole('alert')).toContainText('Invalid');await clear(tool);};
tests['api-auth-header-generator']=async({tool,expect,check})=>{await examples(tool);await expect(tool).toContainText('Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==');await tool.getByRole('button',{name:'API Key',exact:true}).click();await fill(tool,'Api Key','abc123');await fill(tool,'Api Key Name','X-API-Key');await expect(tool).toContainText('X-API-Key: abc123');check(true,'RFC Basic example and custom API-key header match exact outputs');await clear(tool);};
tests['api-endpoint-debugger']=async({tool,expect,check})=>{await examples(tool);await tool.getByRole('button',{name:/fetch/i,exact:false}).click();await expect(pre(tool)).toContainText('https://example.com/users');const code=await pre(tool).textContent();let observed;await vm.runInNewContext(`(async()=>{${code}})()`,{fetch:async(url,options)=>{observed={url,options};return{json:async()=>({})};},console:{log(){}}},{timeout:1000});check(observed.url==='https://example.com/users'&&observed.options.method==='GET','Generated request code calls selected URL and method');await clear(tool);};
tests['api-doc-generator']=async({tool,expect,check})=>{await fill(tool,'Endpoint Name','users');await fill(tool,'Json Input','{"id":1,"active":true,"optional":null}');await tool.getByRole('button',{name:/Generate/}).click();await expect(pre(tool)).toContainText('| `optional` | `null` |');const md=await pre(tool).textContent();check(md.includes('| `active` | `boolean` |')&&md.includes('"id": 1'),'Response documentation preserves null, boolean and example JSON');await clear(tool);};
tests['api-endpoint-documenter']=async({tool,expect,check})=>{await examples(tool);await tool.getByRole('button',{name:'Generate Markdown'}).click();await expect(pre(tool)).toContainText('### 1. GET /users');const md=await pre(tool).textContent();check(md.includes('### 2. POST /users')&&md.includes('"name": "Ada Lovelace"'),'Both endpoints and supplied request example retained');await clear(tool);};
tests['code-beautifier']=async({tool,expect,check})=>{
 const output=tool.getByLabel('Beautified Code',{exact:true});
 for(const [language,input,verify] of [
  ['json','{"a":1,"items":[true,null]}',text=>JSON.stringify(JSON.parse(text))==='{"a":1,"items":[true,null]}'],
  ['javascript','function add(a,b){return a+b;}',text=>vm.runInNewContext(text+';add(2,3)',{},{timeout:1000})===5],
  ['typescript','interface User{name:string}\nfunction greet(user:User):string{return user.name}',text=>text.includes('interface User')&&text.includes('user: User')&&text.includes('): string')],
  ['css','.a{color:red;width:calc(100% - 2px)}',text=>text.includes('color: red')&&text.includes('calc(100% - 2px)')],
  ['html','<div><p>A</p><p>B</p></div>',text=>text.includes('<p>A</p>')&&text.includes('<p>B</p>')],
  ['python','if True:\n    print("keep  spaces")',text=>text==='if True:\n  print("keep  spaces")'],
 ]){
  await tool.getByLabel('Language',{exact:true}).selectOption(language);await fill(tool,'Code',input);
  await tool.getByRole('button',{name:'Beautify',exact:true}).click();await expect(output).toHaveValue(/\n/,{timeout:20000});
  check(verify(await output.inputValue()),`${language} formatting preserves independent expected semantics`);
 }
 await tool.getByLabel('Language',{exact:true}).selectOption('json');await fill(tool,'Code','{');await tool.getByRole('button',{name:'Beautify',exact:true}).click();await expect(output).toHaveValue(/^Error:/);await clear(tool);await expect(output).toHaveCount(0);await expect(tool.getByLabel('Code',{exact:true})).toHaveValue('');
};
tests['code-to-diagram-generator']=async({tool,expect,check})=>{await fill(tool,'Code','start\nfinish');await tool.getByRole('button',{name:/Generate Diagram/}).click();await expect(pre(tool)).toContainText('N1 --> N2');const code=await pre(tool).textContent();check(code.includes('N1["start"]')&&code.includes('N2["finish"]'),'Mermaid source connects the two input steps');await clear(tool);};
tests['url-parameter-extractor']=async({tool,expect,check})=>{await fill(tool,'URL to parse','https://example.com/?q=hello+world&q=%2B#part');await expect(tool.locator('.tb-v2-url-param-val')).toHaveText(['hello world','+']);check(true,'Duplicate query values preserve order and decode plus correctly');await tool.getByRole('button',{name:'Raw',exact:true}).click();await expect(tool.locator('.tb-v2-url-param-val')).toHaveText(['hello+world','%2B']);check(true,'Raw mode preserves original encodings');await fill(tool,'URL to parse','https://example.com/#%ZZ');await tool.getByRole('button',{name:'Decoded',exact:true}).click();await expect(tool.getByRole('alert')).toContainText('Malformed');await clear(tool);};
tests['url-parser']=async({tool,expect,check})=>{await fill(tool,'Input','https://example.com:8443/a?q=hello#part');await expect(tool).toContainText('8443');const text=await tool.innerText();check(text.includes('/a')&&text.includes('?q=hello')&&text.includes('#part'),'Port, path, query and fragment parsed from known URL');await fill(tool,'Input','not a url');await expect(tool).toContainText('Invalid URL');await clear(tool);};
tests['env-parser']=async({tool,expect,check})=>{await fill(tool,'Input','export NAME="Ada Lovelace"\nPORT=3000\nBAD LINE');await expect(tool.locator('tbody tr')).toHaveCount(2);const rows=await tool.locator('tbody tr').allTextContents();check(rows[0].includes('NAME')&&rows[0].includes('Ada Lovelace')&&rows[1].includes('3000'),'Environment parser extracts quoted value and numeric string');await expect(tool).toContainText('Missing "="');await clear(tool);await expect(tool.locator('tbody tr')).toHaveCount(0);};
tests['user-agent-parser']=async({tool,expect,check})=>{await examples(tool);await expect(tool).toContainText('Edge 120.0.2210.91');check((await tool.innerText()).includes('Windows'),'Edge token takes precedence over Chrome/Safari');await fill(tool,'Ua','Mozilla/5.0 (iPad; CPU OS 17_2 like Mac OS X) Version/17.2 Mobile/15E148 Safari/604.1');await expect(tool).toContainText('Safari 17.2');await expect(tool).toContainText('Tablet');check(true,'iPad is a tablet and Safari uses Version token');await clear(tool);};
tests['homoglyph-detector']=async({tool,expect,check})=>{await fill(tool,'Input','pаypal.com');await expect(tool).toContainText('High Risk: 1');check((await tool.innerText()).includes('Cyrillic'),'Cyrillic a is identified in mixed-script hostname');await fill(tool,'Input','paypal.com');await expect(tool).toContainText('High Risk: 0');await clear(tool);};
tests['ldap-filter-generator']=async({tool,expect,check})=>{await examples(tool);await fill(tool,'Row value','A(B)');await expect(pre(tool)).toHaveText('(cn=A\\28B\\29)');check(true,'LDAP parentheses escaped as RFC filter octets');await clear(tool);};
tests['css-class-generator']=async({tool,expect,check})=>{await examples(tool);await expect(pre(tool)).toHaveText('.util-1-display {\n  display: flex;\n}');check(true,'Class generator emits declaration under matching unique selector');await clear(tool);await expect(pre(tool)).toHaveText('');};
tests['docker-command-generator']=async({tool,expect,check})=>{await examples(tool);await fill(tool,'Container Name','hello world');await expect(pre(tool)).toContainText("--name 'hello world'");const cmd=await pre(tool).textContent();check(cmd.includes("-e 'PORT=3000'")&&cmd.includes("'nginx:latest'"),'Docker command quotes whitespace and preserves image/environment');await clear(tool);};
tests['shell-command-generator']=async({tool,expect,check})=>{await tool.getByRole('button',{name:'Git Status',exact:true}).click();await expect(pre(tool)).toHaveText('git status');check(true,'Selected command produces exact git status');await clear(tool);};
tests['curl-command-builder']=async({tool,expect,check})=>{await examples(tool);await expect(pre(tool)).toContainText('-X POST');const code=await pre(tool).textContent();check(code.includes("'https://api.example.com/v1/users'")&&code.includes('Ada Lovelace')&&code.includes('Content-Type: application/json'),'cURL contains selected method, header, URL and body');await clear(tool);await expect(tool.getByLabel('Url',{exact:true})).toHaveValue('');};
tests['curl-gen']=async({tool,expect,check})=>{await fill(tool,'Input','POST /users HTTP/1.1\nHost: example.com\nContent-Type: text/plain\n\nAda');await expect(pre(tool)).toContainText("'https://example.com/users'");const code=await pre(tool).textContent();check(code.includes('-X POST')&&code.includes("-d 'Ada'"),'Raw HTTP request preserves path, method and body');await clear(tool);};
tests['cors-header-generator']=async({tool,expect,check})=>{
 const headers=tool.locator('.tb-v2-tool-output-body').first();
 await tool.getByRole('tab',{name:'With Credentials',exact:true}).click();
 await expect(headers).toContainText(/Access-Control-Allow-Credentials:\s*true/);
 const origin=headers.getByText('Access-Control-Allow-Origin:',{exact:true}).locator('..').locator('span').last();
 await expect(origin).toHaveText('https://example.com');
 const raw=await tool.locator('pre').allTextContents();
 check(raw.some(s=>s.includes('CORS_ALLOW_CREDENTIALS = True')),'Credentialed CORS emits Python True and one exact origin header');
 await tool.getByRole('tab',{name:'Public API',exact:true}).click();await expect(origin).toHaveText('*');await expect(headers.getByText('Access-Control-Allow-Credentials:',{exact:true})).toHaveCount(0);
 const publicCode=await tool.locator('pre').allTextContents();check(publicCode.every(s=>!s.includes('supports_credentials=True')&&!s.includes('CORS_ALLOW_CREDENTIALS = True')&&!s.includes('"credentials": true')),'Public wildcard mode disables credentials in generated framework code');
 await clear(tool);await expect(headers.locator('span')).toHaveCount(0);
};
tests['screen-resolution-tester']=async({tool,expect,check})=>{await fill(tool,'Width','1920');await fill(tool,'Height','1080');await expect(tool).toContainText('2.07 MP');check((await tool.innerText()).includes('1.778'),'1920×1080 gives 2.07 megapixels and 1.778 ratio');await clear(tool);};
tests['screen-density-simulator']=async({tool,expect,check})=>{await examples(tool);await expect(tool).toContainText('physical 720×1280');await tool.getByRole('button',{name:'3x',exact:true}).click();await expect(tool).toContainText('physical 1080×1920');check(true,'Physical dimensions = CSS dimensions × selected DPR');await clear(tool);};
tests['fake-data-generator']=async({tool,expect,check})=>{await fill(tool,'Count','3');await tool.getByRole('button',{name:'email',exact:true}).click();await tool.getByRole('button',{name:'Generate',exact:true}).click();await expect(tool.locator('tbody tr')).toHaveCount(3);check((await tool.locator('tbody td').allTextContents()).every(s=>/^[^@\s]+@example\.(com|org|net)$/.test(s)),'Exactly three sample emails use reserved domains');await clear(tool);await expect(tool.locator('tbody tr')).toHaveCount(0);};
tests['random-string-generator']=async({tool,expect,check})=>{await fill(tool,'Length','8');await fill(tool,'Count','3');await tool.getByLabel('Charset Key',{exact:true}).selectOption('numbers');await tool.getByRole('button',{name:'Generate',exact:true}).click();const strings=tool.locator('.break-all.flex-1');await expect(strings).toHaveCount(3);check((await strings.allTextContents()).every(x=>/^\d{8}$/.test(x)),'Three random strings have exactly eight digits');await tool.getByRole('button',{name:'UUID',exact:true}).click();await expect(strings).toHaveCount(1);check(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(await strings.innerText()),'UUID uses RFC v4 version and variant bits');await clear(tool);};
tests['email-generator']=async({tool,expect,check})=>{await examples(tool);await fill(tool,'Count','3');await tool.getByRole('button',{name:'Generate Emails',exact:true}).click();const emails=tool.locator('span.font-mono');await expect(emails).toHaveCount(3);check((await emails.allTextContents()).every(s=>/^[a-z]+\.[a-z]+@example.com$/.test(s)),'Three first.last addresses match selected reserved domain');await clear(tool);};
tests['algorithm-visualizer']=async({tool,expect,check})=>{await examples(tool);await tool.getByLabel('Speed',{exact:true}).selectOption('50');for(const name of ['Bubble Sort','Selection Sort','Insertion Sort']){await tool.getByRole('button',{name,exact:true}).click();await tool.getByRole('button',{name:`Start ${name}`,exact:true}).click();await expect(tool).toContainText('Sorted!');const values=await tool.locator('.h-48 span').allTextContents();check(values.map(x=>Number(x.trim())).join(',')==='1,2,3',`${name} sorts [3,1,2] to [1,2,3]`);}await clear(tool);};
tests['shell-command-reference']=async({tool,expect,check})=>{await fill(tool,'Search','pwd');await expect(tool.locator('code').filter({hasText:/^pwd$/})).toBeVisible();check((await tool.innerText()).toLowerCase().includes('directory'),'pwd reference describes current directory');await clear(tool);};
tests['mime-types-reference']=async({tool,expect,check})=>{await fill(tool,'Search','json');await expect(tool).toContainText('application/json');const rows=await tool.locator('tbody tr').allTextContents();check(rows.some(r=>r.includes('.json')&&r.includes('application/json')),'JSON extension maps to application/json in same row');await clear(tool);};
tests['http-status-checker']=async({tool,baseURL,page,expect,check})=>{await fill(tool,'URL',new URL('/api/health',baseURL).href);await tool.getByRole('button',{name:'Inspect',exact:true}).click();await expect(tool.getByTestId('http-status')).toContainText('HTTP 200',{timeout:15000});const headers=JSON.parse(await pre(tool).textContent());check(headers['content-type'].includes('application/json'),'Actual health response has HTTP 200 and JSON content type');await fill(tool,'URL','https://httpbin.org/get');await tool.getByRole('button',{name:'Inspect',exact:true}).click();await expect(tool.getByTestId('http-status')).toContainText('HTTP 200',{timeout:15000});check((await pre(tool).textContent()).includes('application/json'),'Real public read-only HTTP endpoint returns JSON response headers');await fill(tool,'URL','file:///bad');await tool.getByRole('button',{name:'Inspect',exact:true}).click();await expect(tool.getByRole('alert')).toContainText('HTTP(S)');await clear(tool);await expect(tool.getByTestId('http-status')).toHaveCount(0);};
tests['graphql-playground']=async({tool,expect,check})=>{await examples(tool);await fill(tool,'Variables','[]');await tool.getByRole('button',{name:'Run Query',exact:true}).click();await expect(tool).toContainText('Expected a JSON object');await clear(tool);await expect(tool.getByLabel('Endpoint',{exact:true})).toHaveValue('');check(true,'Invalid variables rejected and Clear resets the endpoint');await examples(tool);await tool.getByRole('button',{name:'Run Query',exact:true}).click();await expect(pre(tool)).toContainText('Bangladesh',{timeout:15000});const response=JSON.parse(await pre(tool).textContent());check(response.data.country.name==='Bangladesh'&&response.data.country.capital==='Dhaka','Real read-only GraphQL country query returns Bangladesh/Dhaka');await fill(tool,'Variables','[]');await tool.getByRole('button',{name:'Run Query',exact:true}).click();await expect(tool).toContainText('Expected a JSON object');await clear(tool);};
tests['websocket-tester']=async({tool,expect,check})=>{await fill(tool,'Url','https://example.com');await tool.getByRole('button',{name:'Connect',exact:true}).click();await expect(tool).toContainText('Enter a ws:// or wss:// URL');await clear(tool);await expect(tool.getByLabel('Url',{exact:true})).toHaveValue('');check(true,'Non-WebSocket URL rejected and Clear resets URL');await examples(tool);await tool.getByRole('button',{name:'Connect',exact:true}).click();await expect(tool.getByRole('button',{name:'Send',exact:true})).toBeEnabled({timeout:15000});await fill(tool,'Message','toolblip-qa-echo-61');await tool.getByRole('button',{name:'Send',exact:true}).click();await expect.poll(async()=> (await tool.innerText()).split('toolblip-qa-echo-61').length).toBeGreaterThanOrEqual(3);check((await tool.innerText()).split('toolblip-qa-echo-61').length>=3,'Live echo endpoint returns the message that was sent');await clear(tool);await expect(tool).toContainText('Disconnected');};
const aliases={
 'cron-human-readable':'cron-parser','cron-schedule-generator':'cron-parser','cron-schedule-validator':'cron-parser','cron-validator':'cron-parser','cron-generator-dg':'cron-parser','cron-schedule-explainer':'cron-parser',
 'regex-pattern-tester':'regex-tester','regex-match-tester':'regex-tester','regex-match-visualizer':'regex-tester','regex-description-generator':'regex-explainer',
 'http-headers-inspector':'http-status-checker','url-redirect-checker':'http-status-checker',
};
const slugs = [
'css-class-generator','url-parameter-extractor','cron-parser','cors-header-generator','screen-resolution-tester','regex-tester','cron-generator','js-minifier','fake-data-generator','random-string-generator','url-parser','css-validator','html-validator','email-generator','semver-checker','html-table-generator','homoglyph-detector','shell-command-reference','user-agent-parser','graphql-playground','websocket-tester','ldap-filter-generator','regex-pattern-generator','css-to-scss','env-parser','mime-types-reference','docker-command-generator','html-live-preview','code-beautifier','css-to-tailwind','css-to-styled-components','url-redirect-checker','api-spec-generator','regex-description-generator','regex-match-visualizer','cron-human-readable','curl-gen','regex-pattern-tester','cron-schedule-generator','regex-explainer','cron-schedule-validator','api-auth-header-generator','cron-validator','css-minifier','html-minifier','code-to-diagram-generator','algorithm-visualizer','http-headers-inspector','api-doc-generator','api-endpoint-debugger','screen-density-simulator','cron-generator-dg','regex-pattern-builder','cron-schedule-explainer','curl-to-python','curl-to-javascript','http-status-checker','shell-command-generator','api-endpoint-documenter','curl-command-builder','regex-match-tester'];
export default slugs.map(slug=>({slug,requiresExample:true,requiresClear:true,async test(ctx){await tests[aliases[slug]??slug](ctx);if(slug==='code-beautifier'){await typescriptDownload({...ctx,slug});ctx.check(true,'Downloaded .ts bytes retain exported type/interface declarations and TypeScript minification preserves them');await clear(ctx.tool);}ctx.check(checkedPopulatedMobile.has(ctx.tool),'Populated result or error state fits a 320px viewport before Clear');const previous=ctx.page.viewportSize();await ctx.page.setViewportSize({width:320,height:800});const fits=await ctx.tool.evaluate(el=>el.scrollWidth<=el.clientWidth+1);ctx.check(fits,'Tool contents fit a 320px viewport');if(previous)await ctx.page.setViewportSize(previous);}}));
