import { stickyPersistence } from '../regressions/misc-review.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';
import { isIP } from 'node:net';
import XLSX from 'xlsx';
import { PDFDocument } from 'pdf-lib';
import { load as yamlLoad } from 'js-yaml';
import { probeNativeSpeech } from '../helpers/utility-design-speech.mjs';
const example = t => t.getByRole('button', {name:/^Examples?$/}).click();
const clear = t => t.getByRole('button', {name:'Clear',exact:true}).click();
const fill = (t,n,v) => t.getByLabel(n,{exact:true}).fill(v);
const click = (t,n) => t.getByRole('button',{name:n,exact:typeof n==='string'}).click();
const output = t => t.locator('.tb-v2-tool-output-body').last();
async function download(ctx, name) {
  const control=ctx.tool.getByRole('button',{name,exact:typeof name==='string'}).or(ctx.tool.getByRole('link',{name,exact:typeof name==='string'}));
  const [d]=await Promise.all([ctx.page.waitForEvent('download'),control.click()]); await fs.mkdir(ctx.artifactsDir,{recursive:true});
  const target=path.join(ctx.artifactsDir,`${Date.now()}-${d.suggestedFilename()}`); await d.saveAs(target);
  return fs.readFile(target);
}
async function png(ctx, name, dimensions) {
  const b=await download(ctx,name);
  ctx.check(b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),'Download is genuine PNG');
  const w=b.readUInt32BE(16),h=b.readUInt32BE(20);
  ctx.check(dimensions? w===dimensions[0]&&h===dimensions[1]:w>0&&h>0,`PNG dimensions ${w}×${h}`);
  const colors=await ctx.page.evaluate(async data=>{const image=new Image();image.src='data:image/png;base64,'+data;await image.decode();const c=document.createElement('canvas');c.width=image.width;c.height=image.height;const x=c.getContext('2d');x.drawImage(image,0,0);const p=x.getImageData(0,0,c.width,c.height).data;const colors=new Set();for(let i=0;i<p.length;i+=4) colors.add(`${p[i]},${p[i+1]},${p[i+2]},${p[i+3]}`);return colors.size;},b.toString('base64'));
  ctx.check(colors>1,'Decoded PNG contains nonblank rendered pixels');return b;
}
const cases=[];
function add(slug,test,options={}) {
 cases.push({slug,...options,async test(ctx){
   await test(ctx);
   if(slug==='sticky-notes'){await stickyPersistence(ctx);ctx.check(true,'All 101 legacy notes and extra fields survive reload; add limit is enforced without truncating storage and explicit deletion persists');}
   // Layout assertion supplements each route's functional assertions.
   const previous=ctx.page.viewportSize();await ctx.page.setViewportSize({width:320,height:800});
   ctx.check(await ctx.tool.evaluate(e=>e.scrollWidth<=e.clientWidth+2),'Tool fits a 320px viewport');
   if(previous)await ctx.page.setViewportSize(previous);
 }});
}
for(const slug of ['html-encoder','html-entity-encoder']) add(slug,async c=>{
 const {tool:t,expect,check}=c;await example(t);const input=t.getByRole('textbox');
 await input.fill('<b>"A&B"</b>');await expect(t.locator('pre')).toHaveText('&lt;b&gt;&quot;A&amp;B&quot;&lt;/b&gt;');
 await click(t,'Decode');await input.fill('&amp;lt; &#x1f600; &#99999999;');await expect(t.locator('pre')).toContainText('&lt; 😀 �');
 check(true,'Single-pass entity decoding preserves literal entities and handles invalid code points');await clear(t);await expect(input).toHaveValue('');
});
add('css-border-radius-generator',async({tool:t,expect,check})=>{await click(t,'Circle');await expect(t.locator('pre')).toContainText('border-radius: 50%;');await expect(t.getByLabel('Border radius preview')).toHaveCSS('border-top-left-radius','50%');check(true,'Circle preset matches emitted CSS and preview');await clear(t);await expect(t.locator('pre')).toContainText('border-radius: 0px;');});
add('sass-to-css',async({tool:t,expect,check})=>{await example(t);await click(t,'Compile');await expect(t.locator('pre')).toContainText('color: red;',{timeout:10000});await fill(t,'SASS/SCSS input','$x: 4px; .a { .b { padding: $x * 2; } }');await click(t,'Compile');await expect(t.locator('pre')).toContainText('padding: 8px;',{timeout:10000});await expect(t.locator('pre')).toContainText('.a .b');await fill(t,'SASS/SCSS input','.a { color:');await click(t,'Compile');await expect(t.getByRole('alert')).toBeVisible();await clear(t);await expect(t.locator('pre')).toHaveText('-');check(true,'Real Sass nesting/arithmetic, invalid syntax, and reset');});
add('random-number-generator',async({tool:t,expect,check})=>{await fill(t,'Minimum value','0');await fill(t,'Maximum value','0');await fill(t,'Number of values','1');await click(t,'Generate');await expect(output(t)).toHaveText('0');await fill(t,'Minimum value','4');await click(t,'Generate');await expect(t.getByRole('alert')).toContainText('safe integer');check(true,'Zero maximum is not replaced by 100; reversed bounds rejected');await clear(t);await expect(t.getByLabel('Minimum value')).toHaveValue('');});
for(const slug of ['uptime-calculator','sla-uptime-calculator'])add(slug,async({tool:t,expect,check})=>{await example(t);await expect(output(t)).toContainText('1.4400 minutes');await expect(output(t)).toContainText('3.6 sec');await t.getByRole('spinbutton').fill('100');await expect(output(t)).toContainText('0.0000 minutes');await t.getByRole('spinbutton').fill('101');await expect(t.getByRole('alert')).toBeVisible();await clear(t);check(true,'99.9% day downtime is 1.44 minutes; hourly units are seconds, 100% and invalid SLA covered');});
add('age-calculator',async({tool:t,expect,check})=>{await example(t);await expect(t.getByText('24',{exact:true})).toBeVisible();await fill(t,'Birth date input','2024-01-31');await fill(t,'As of date','2024-03-01');await expect(t.getByText('30',{exact:true})).toBeVisible();await fill(t,'Birth date input','2025-01-01');await expect(t.getByText('Birth date cannot be after the target date.')).toBeVisible();await clear(t);check(true,'Date-only age covers leap birthday, month-end 30-day interval and future rejection');});
add('countdown-timer',async c=>{const {page,tool:t,expect,check}=c;await page.clock.install();await example(t);await click(t,'Start');await page.clock.fastForward(2000);await expect(t.getByText('00:00:03',{exact:true})).toBeVisible();await click(t,'Pause');await page.clock.fastForward(3000);await expect(t.getByText('00:00:03',{exact:true})).toBeVisible();await click(t,'Start');await page.clock.fastForward(1000);await expect(t.getByText('00:00:02',{exact:true})).toBeVisible();await clear(t);await page.clock.fastForward(6000);await expect(t.getByText('00:00:00',{exact:true})).toBeVisible();check(true,'Clock-controlled countdown pauses, resumes and cancels on Clear');});
add('text-to-handwriting',async({tool:t,expect,check})=>{await example(t);await fill(t,'Input','Handwriting QA 123');const preview=t.getByText('Handwriting QA 123',{exact:true}).filter({hasNot:t.locator('textarea')});await expect(preview.last()).toBeVisible();await t.getByLabel('Font Size').focus();await t.getByLabel('Font Size').press('Home');for(let i=0;i<20;i++)await t.getByLabel('Font Size').press('ArrowRight');check(await preview.last().evaluate(e=>getComputedStyle(e).fontSize==='32px'),'Preview uses selected font size; copy is explicitly plain text');await clear(t);await expect(t.getByLabel('Input')).toHaveValue('');});
add('random-ip-address',async({tool:t,expect,check})=>{await example(t);await click(t,'Generate IPv4 Addresses');const text=await output(t).innerText();const ips=text.trim().split(/\s+/);check(ips.length===5&&ips.every(x=>isIP(x)===4),'Five valid IPv4 addresses');await clear(t);await expect(output(t)).toContainText('Click Generate');});
add('ipv6-generator',async({tool:t,expect,check})=>{for(const format of ['full','compressed','eui64']){await t.getByLabel('IPv6 format').selectOption(format);await fill(t,'Count','4');await click(t,'Generate');const ips=(await output(t).innerText()).trim().split(/\s+/);check(ips.length===4&&ips.every(x=>isIP(x)===6),`${format} yields four valid 128-bit addresses`);if(format==='eui64')check(ips.every(x=>x.split(':')[5].endsWith('ff')&&x.split(':')[6].startsWith('fe')),'EUI-64 includes ff:fe insertion');}await clear(t);await expect(t.locator('.tb-v2-tool-output-body')).toHaveCount(0);});
add('slideshow-generator',async c=>{await c.expect(c.tool.getByLabel('Active title')).toHaveValue('Slide 1');for(const title of ['Slide 3','Slide 4']){await click(c.tool,'+ Add Slide');await c.expect(c.tool.getByLabel('Active title')).toHaveValue(title);}await example(c.tool);const b=await download(c,/Download.*HTML/i);const html=b.toString();c.check(html.includes('<h1>Welcome</h1>')&&html.includes('<h1>Next steps</h1>'),'HTML download contains both supplied slides');
 const exported=await c.page.context().newPage();try{await exported.setContent(html);await c.expect(exported.getByRole('heading',{name:'Welcome',exact:true})).toBeVisible();await exported.getByRole('button',{name:/Next/}).click();await c.expect(exported.getByRole('heading',{name:'Next steps',exact:true})).toBeVisible();await exported.getByRole('button',{name:/Prev/}).click();await c.expect(exported.getByRole('heading',{name:'Welcome',exact:true})).toBeVisible();c.check(true,'Downloaded standalone HTML executes Next/Prev navigation independently of the app');}finally{await exported.close();}
 await clear(c.tool);await c.expect(c.tool.getByLabel('Active title')).toHaveValue('');});
add('quote-of-the-day',async({tool:t,expect,check})=>{const quote=t.locator('p').first();const initial=await quote.innerText();await click(t,'Shuffle / Random Quote');await expect(quote).not.toHaveText(initial);await click(t,"Back to Today's Quote");await expect(quote).toHaveText(initial);check(true,'Shuffle changes quote and daily reset restores exact quote');},{requiresExample:false,requiresClear:false,exceptionReason:'Reference-only quote reader: Shuffle and Back to Today replace Example/Clear.'});
add('time-zone-converter',async({tool:t,expect,check})=>{await example(t);await expect(t.getByText('2024-07-01 17:00',{exact:true})).toBeVisible();await expect(t.getByText('2024-07-02 01:00',{exact:true})).toBeVisible();await fill(t,'Input Date','2024-03-10');await fill(t,'Input Time','02:30');await expect(t.getByRole('alert')).toContainText('does not exist');await fill(t,'Input Date','2024-11-03');await fill(t,'Input Time','01:30');await expect(t.getByRole('alert')).toContainText('twice');await clear(t);await expect(t.getByRole('alert')).toHaveCount(0);check(true,'Summer NY/London/Tokyo conversion and both DST ambiguity paths');});
add('random-fraction-generator',async({tool:t,expect,check})=>{await example(t);const rows=output(t).locator('div > div').filter({has:t.locator('span')});const fractions=(await output(t).innerText()).match(/\d+\/\d+/g)||[];check(fractions.length===10&&fractions.every(f=>{const [n,d]=f.split('/').map(Number);return d>0&&n/d>=.5&&n/d<=5/6;}),'Ten fractions actually lie in [1/2,5/6]');await fill(t,'Minimum value','1/0');await click(t,/Generate/);await expect(t.getByText(/non-negative minimum/)).toBeVisible();await clear(t);await expect(output(t)).toContainText('Choose a range');});
add('physics-constants-reference',async({tool:t,expect,check})=>{await example(t);const row=t.getByRole('button').filter({hasText:'Speed of light'});await expect(row).toContainText('299792458');await expect(row).toContainText('m/s');await fill(t,'Search','no-such-constant-qa');await expect(t.getByRole('button').filter({hasText:'Speed of light'})).toHaveCount(0);await clear(t);await expect(t.getByRole('button').filter({hasText:'Planck constant'}).first()).toBeVisible();check(true,'Filtered reference returns the exact SI speed of light and clears filters');});
// Browser support and fixture-controlled lifecycle are deliberately separate evidence.
add('speech-to-text',async c=>{const {tool:t,page,expect,check}=c;
 const native=await probeNativeSpeech(c,'recognition');
 const supported=native.supported;
 if(!supported)await expect(t.getByRole('status')).toContainText('not supported');
 check(true,supported?'Recognition API present; real microphone/service acceptance remains unverified':'Observed honest unsupported state; no real recognition claimed');
 await example(t);await click(t,'Use This Text');await expect(t.getByLabel('Transcript',{exact:true})).toHaveText('This is an example transcript, not microphone recognition.');await clear(t);await expect(t.getByLabel('Transcript',{exact:true})).toHaveText('');
 // Controlled API fixture tests event handling, not speech recognition accuracy.
 const fixturePage=await page.context().newPage(); const fixtureTool=fixturePage.locator('.tb-v2-tool-card').first();
 try {
 await fixturePage.addInitScript(()=>{class Recognition{start(){window.__recognition=this;this.onstart?.();}stop(){this.onend?.();}abort(){this.onend?.();}}window.SpeechRecognition=Recognition;});await fixturePage.goto(page.url());await click(fixtureTool,'Start Listening');
 await fixturePage.evaluate(()=>{const r=window.__recognition;r.onresult({results:[Object.assign([{transcript:'hello'}],{isFinal:true})]});r.onresult({results:[Object.assign([{transcript:'hello'}],{isFinal:true}),Object.assign([{transcript:'world'}],{isFinal:true})]});});
 await expect(fixtureTool.getByLabel('Transcript',{exact:true})).toHaveText('hello world');await clear(fixtureTool);await fixturePage.evaluate(()=>window.__recognition.onresult({results:[[{transcript:'late'}]]}));await expect(fixtureTool.getByLabel('Transcript',{exact:true})).toHaveText('');check(true,'Fixture-only lifecycle: finalized results do not duplicate; Clear rejects late events');
 } finally { await fixturePage.close(); }
 check(false,'Human review required: speak known words into a real microphone and verify the actual recognized transcript; mocked lifecycle events do not establish recognition accuracy.');
});
add('sticky-notes',async({tool:t,page,expect,check})=>{await example(t);await expect(t.getByText('Example: review the project checklist.',{exact:true})).toBeVisible();await page.reload();await expect(t.getByText('Example: review the project checklist.',{exact:true})).toBeVisible();await clear(t);await page.reload();await expect(t.getByText('Example: review the project checklist.',{exact:true})).toHaveCount(0);check(true,'Notes persist across reload and Clear removes persisted content');});
add('css-grid-generator',async({tool:t,expect,check})=>{await click(t,'Card Grid');await expect(t.locator('pre').first()).toContainText('grid-template-rows: auto;');await fill(t,'Columns','2');await fill(t,'Rows','3');await expect(t.locator('pre').first()).toContainText('grid-template-columns: repeat(2, 1fr);');await expect(t.locator('pre').last()).toContainText('Item 6');await clear(t);await expect(t.locator('pre').first()).toContainText('gap: 0px;');check(true,'Auto row preset and 2×3 CSS/HTML output agree');});
add('css-flexbox-generator',async({tool:t,expect,check})=>{await example(t);await expect(t.locator('pre')).toContainText('justify-content: space-between;');await t.getByLabel('Direction').selectOption('column');await expect(t.locator('pre')).toContainText('flex-direction: column;');await clear(t);await expect(t.locator('pre')).toContainText('gap: 0px;');check(true,'Flexbox direction, spacing and reset reach exported CSS');});
add('word-cloud-generator',async c=>{const {tool:t,expect,check}=c;await fill(t,'Input','apple apple banana');await click(t,'Generate Word Cloud');const vals=await t.locator('.tb-v2-stat-pill-val').allTextContents();check(vals[0]==='3'&&vals[1]==='2','Word cloud counts three filtered words and two unique words');await png(c,'Download PNG',[760,440]);await fill(t,'Input','pear');await expect(t.getByRole('button',{name:'Download PNG'})).toBeDisabled();await clear(t);await expect(t.getByLabel('Input')).toHaveValue('');});
add('english-dictionary',async c=>{const {page,tool:t,expect,check}=c;
 // Only a controlled failure is intercepted. Live definitions are not fabricated.
 let intercepted=false;await page.route('https://freedictionaryapi.com/api/v1/entries/en/**',r=>{intercepted=true;return c.abortExpectedRequest(r, 'Intentional dictionary lookup failure verifies error and recovery');});await fill(t,'Word','hello');await click(t,/Look Up|Search|Lookup/i);await expect(t.getByText('Lookup unavailable or timed out. Try again.')).toBeVisible();await clear(t);await expect(t.getByLabel('Word')).toHaveValue('');check(intercepted,'The intended dictionary provider request was aborted; the visible failure and Clear recovery both passed');await page.unroute('https://freedictionaryapi.com/api/v1/entries/en/**');
 await example(t);await expect(t.getByText('eloquent',{exact:true}).first()).toBeVisible({timeout:35000});await expect(t.getByText('Fluently persuasive and articulate.',{exact:true})).toBeVisible();await expect(t.getByLabel('IPA pronunciation')).toContainText('kw');await expect(t.getByText('well-spoken',{exact:true})).toBeVisible();await expect(t.getByRole('link',{name:'FreeDictionaryAPI.com',exact:true})).toHaveAttribute('href','https://freedictionaryapi.com');await expect(t.getByRole('link',{name:'Original Wiktionary entry',exact:true})).toHaveAttribute('href','https://en.wiktionary.org/wiki/eloquent');await expect(t.getByRole('link',{name:'CC BY-SA 4.0',exact:true})).toHaveAttribute('href','https://creativecommons.org/licenses/by-sa/4.0/');await expect(t.getByRole('button',{name:'Play',exact:true})).toHaveCount(0);check(true,'Live dictionary returns the exact eloquent definition, IPA and synonym, with original-source/provider/license attribution and no fabricated audio');
});
add('text-to-speech',async c=>{const {page,tool:t,expect,check}=c;const native=await probeNativeSpeech(c,'synthesis');const available=native.supported;if(!available)await expect(t.getByRole('status')).toContainText('not supported');check(true,available?'Synthesis API present; audible output remains unverified':'Observed unsupported synthesis state');
 const fixturePage=await page.context().newPage(); const fixtureTool=fixturePage.locator('.tb-v2-tool-card').first();
 try {
 await fixturePage.addInitScript(()=>{class Utterance{constructor(text){this.text=text;}}window.SpeechSynthesisUtterance=Utterance;Object.defineProperty(window,'speechSynthesis',{configurable:true,value:{getVoices:()=>[],addEventListener(){},removeEventListener(){},cancel(){window.__cancelled=true;},speak(u){window.__utterance=u;u.onstart?.();}}});});await fixturePage.goto(page.url());await example(fixtureTool);await click(fixtureTool,/Speak/);await expect(fixtureTool.getByRole('button',{name:/Stop/})).toBeVisible();check(await fixturePage.evaluate(()=>window.__utterance.text.includes('browser speech synthesis')),'Fixture-only synthesis receives actual entered text');await clear(fixtureTool);await fixturePage.evaluate(()=>window.__utterance.onstart?.());await expect(fixtureTool.getByRole('button',{name:/Speak/})).toBeDisabled();check(await fixturePage.evaluate(()=>window.__cancelled),'Clear cancels fixture synthesis and ignores stale start');
 } finally { await fixturePage.close(); }
 check(false,'Human review required: listen to actual synthesized audio and verify it matches the entered text; mocked lifecycle events do not establish audible output.');
});
add('collocations-checker',async({tool:t,expect,check})=>{await fill(t,'Text','make a decision and take into account');await click(t,'Check Collocations');await expect(output(t)).toContainText('make a decision');await expect(output(t)).toContainText('take into account');await fill(t,'Text','make');await click(t,'Check Collocations');await expect(t.getByText('make a decision',{exact:true})).toHaveCount(0);await clear(t);check(true,'Complete phrase matching supports four words and does not invent a phrase for make');});
add('automation-wizard',async({tool:t,page,expect,check})=>{await page.context().grantPermissions(page.context().browser()?.browserType().name()==='webkit'?['clipboard-read']:['clipboard-read','clipboard-write']);await example(t);await click(t,'Copy YAML');await expect.poll(()=>page.evaluate(()=>navigator.clipboard.readText())).toContain('Daily report');const parsed=yamlLoad(await page.evaluate(()=>navigator.clipboard.readText()));check(parsed.trigger.name==='Daily report'&&parsed.trigger.config.interval==='daily'&&parsed.trigger.config.time==='09:00','YAML retains workflow name and all configured schedule fields');await clear(t);await expect(t.getByRole('button',{name:'Copy YAML'})).toHaveCount(0);});
add('bill-sale-generator',async c=>{await example(c.tool);await click(c.tool,'Generate Bill of Sale');const b=await download(c,'Download TXT');const txt=b.toString();c.check(txt.includes('Alex Seller')&&txt.includes('Sam Buyer')&&txt.includes('B-101')&&txt.includes('210.00'),'Bill of sale download includes supplied parties, item and price plus tax');await fill(c.tool,'Sale Price ($)','-1');await click(c.tool,'Generate Bill of Sale');await c.expect(c.tool.getByRole('alert')).toBeVisible();await clear(c.tool);await c.expect(c.tool.getByRole('button',{name:'Download TXT'})).toHaveCount(0);});
add('business-plan-generator',async({tool:t,expect,check})=>{await fill(t,'Business idea','Bicycle repair studio');await fill(t,'Target market','local commuters');await t.getByLabel('Budget level').selectOption('low');await click(t,'Generate Business Plan');await expect(output(t)).toContainText('Bicycle repair studio');await expect(output(t)).toContainText('local commuters');await expect(output(t)).toContainText('low budget');await expect(output(t)).not.toContainText('50% revenue increase');await clear(t);await expect(t.getByLabel('Business idea')).toHaveValue('');check(true,'Outline reflects all supplied inputs and does not fabricate financial projections');});
add('chart-maker',async c=>{await example(c.tool);await click(c.tool,'Pie');await png(c,'Download Chart');await c.expect(c.tool.getByText('Q1: 10',{exact:true})).toBeVisible();await c.expect(c.tool.getByText('Q2: 20',{exact:true})).toBeVisible();await clear(c.tool);await c.expect(c.tool.getByLabel('Chart title')).toHaveValue('');c.check(true,'Pie PNG decodes and current data labels are present; Clear removes dataset');});
for(const [slug,fields,needles] of [
 ['nda-generator',[['Discloser','QA Discloser'],['Receiver','QA Receiver'],['Purpose','reviewing prototype ZX9'],['Governing State','Oregon']],['QA Discloser','QA Receiver','prototype ZX9','Oregon']],
 ['press-release-generator',[['Headline','QA Workshop Opens'],['Body','First paragraph.\n\nSecond paragraph.'],['Contact Email','qa@example.com']],['QA Workshop Opens','First paragraph.','Second paragraph.','qa@example.com']],
 ['privacy-policy-generator',[['Company Name','QA Company'],['Website Url','https://qa.example.com'],['Contact Email','privacy@qa.example.com'],['Third Party Services','QA Analytics']],['QA COMPANY','https://qa.example.com','privacy@qa.example.com','QA Analytics']],
 ['purchase-agreement-generator',[['Buyer Name','QA Buyer'],['Seller Name','QA Seller'],['Item Description','Prototype ZX9'],['Price','250'],['Payment Terms','Payment at delivery']],['QA Buyer','QA Seller','Prototype ZX9','$250.00','Payment at delivery']],
]) add(slug,async c=>{await example(c.tool);for(const [n,v]of fields)await fill(c.tool,n,v);const txt=(await download(c,'Download .txt')).toString();c.check(needles.every(n=>txt.includes(n)),'TXT export preserves every tested field');const pdf=await download(c,'Download .pdf');const doc=await PDFDocument.load(pdf);c.check(doc.getPageCount()>0,'PDF bytes parse as a real paginated PDF');
 const {getDocument}=await import('pdfjs-dist/legacy/build/pdf.mjs');const loadingTask=getDocument({data:Uint8Array.from(pdf),useSystemFonts:true});const reader=await loadingTask.promise;
 try {let extracted='';for(let i=1;i<=reader.numPages;i++){const page=await reader.getPage(i);extracted+=(await page.getTextContent()).items.map(item=>item.str||'').join(' ');}
 const compact=value=>value.replace(/\s+/g,'');c.check(needles.every(n=>compact(extracted).includes(compact(n))),'Independent PDF.js extraction preserves every tested document field');}finally{await loadingTask.destroy();}
 await fill(c.tool,fields[0][0],'বাংলা');await click(c.tool,'Download .pdf');await c.expect(c.tool.getByRole('alert')).toContainText('Download TXT');await clear(c.tool);await c.expect(c.tool.getByRole('button',{name:'Download .txt',exact:true})).toBeDisabled();});
add('poll-generator',async({tool:t,expect,check})=>{await example(t);await t.getByRole('tab',{name:'Survey',exact:true}).click();await click(t,'Process');await expect(t.getByLabel('Output',{exact:true})).toHaveValue(/1\. Apple/);await expect(t.getByLabel('Output',{exact:true})).toHaveValue(/2\. Pear/);await expect(t.getByLabel('Output',{exact:true})).toHaveValue(/3\. Plum/);await expect(t.getByLabel('Output',{exact:true})).not.toHaveValue(/Strongly disagree/);await clear(t);check(true,'Survey preserves supplied options instead of replacing them with default scale');});
add('split-csv',async c=>{const t=c.tool;await t.getByLabel('Upload file').setInputFiles({name:'quoted.csv',mimeType:'text/csv',buffer:Buffer.from('name,note\r\n"Ada, A","line1\nline2"\r\nLin,"say ""hi"""\r\n')});const b=await download(c,/Download 1 CSV Files/);c.check(b.toString()==='name,note\n"Ada, A","line1\nline2"\nLin,"say ""hi"""','CSV bytes preserve embedded newline, commas and escaped quotes');await t.getByLabel('Upload file').setInputFiles({name:'bad.csv',mimeType:'text/csv',buffer:Buffer.from('x\n"open')});await c.expect(t.getByText(/malformed/)).toBeVisible();await clear(t);await c.expect(t.getByRole('button',{name:/Download.*CSV/})).toHaveCount(0);});
add('split-excel',async c=>{const t=c.tool;await example(t);const b=await download(c,/Download 1 Excel Files/);const wb=XLSX.read(b,{type:'buffer'});c.check(JSON.stringify(XLSX.utils.sheet_to_json(wb.Sheets.People,{header:1}))===JSON.stringify([['Name','Count'],['Ada',2],['Lin',3]]),'Downloaded XLSX opens and preserves numeric values and header');await t.getByLabel('Upload file').setInputFiles({name:'fake.xlsx',mimeType:'application/octet-stream',buffer:Buffer.from('not an Excel workbook')});await c.expect(t.getByText('This is not an XLSX ZIP workbook.')).toBeVisible();await clear(t);});
add('zip',async c=>{await example(c.tool);await click(c.tool,/Create ZIP/);const b=await download(c,'Download');const zip=XLSX.CFB.read(b,{type:'buffer'});const files=zip.FileIndex.filter(f=>f.content?.length);c.check(files.some(f=>f.name==='hello.txt'&&Buffer.from(f.content).toString()==='Hello from Toolblip!')&&files.some(f=>f.name==='notes.txt'&&Buffer.from(f.content).toString().includes('second example file')),'Independent ZIP reader extracts both original file contents');await clear(c.tool);await c.expect(c.tool.getByRole('link',{name:/Download/})).toHaveCount(0);});
add('random-choice-wheel',async c=>{const {tool:t,expect,check}=c;await example(t);await t.getByLabel('C weight',{exact:true}).nth(0).fill('0');await t.getByLabel('C weight',{exact:true}).nth(1).fill('1');await click(t,'Spin the Wheel');await expect(t.locator('.tb-v2-stat-pill-val')).toHaveText('Coffee',{timeout:10000});await click(t,'Spin the Wheel');await clear(t);await expect(t.getByRole('button',{name:'Spin the Wheel'})).toBeDisabled();check(true,'Zero-weight choice cannot win; Clear cancels animation');});
add('image-shadow-generator',async c=>{await example(c.tool);await c.expect(c.tool.getByAltText('Shadow',{exact:true})).toBeVisible();await png(c,'Download',[180,140]);await clear(c.tool);await c.expect(c.tool.getByAltText('Shadow',{exact:true})).toHaveCount(0);c.check(true,'Rendered PNG adds correct transparent shadow padding and Clear removes result');});
add('css-naming-convention',async({tool:t,expect,check})=>{await fill(t,'Input','XMLHttpRequest');await expect(t.locator('code').nth(0)).toHaveText('xml-http-request');await expect(t.locator('code').nth(1)).toHaveText('xmlHttpRequest');await expect(t.locator('code').nth(4)).toHaveText('XML_HTTP_REQUEST');await clear(t);await expect(t.locator('code')).toHaveCount(0);check(true,'Acronyms split into complete words in kebab, camel and constant case');});
for(const [slug,pattern]of [['random-pin-generator',/^\d{6}$/],['random-id-generator',/^item_[A-Za-z0-9]{8}$/]])add(slug,async({tool:t,expect,check})=>{await example(t);await click(t,/Generate/);const values=(await t.locator('pre').innerText()).trim().split('\n');check(values.length===3&&values.every(v=>pattern.test(v)),'Generated count, alphabet, length and prefix match controls');await clear(t);await expect(t.locator('pre')).toHaveCount(0);});
add('time-duration-calculator',async({tool:t,expect,check})=>{await example(t);await expect(output(t)).toContainText('1:30:00');await expect(output(t)).toContainText('+1 day');await fill(t,'Start','25:00:00');await expect(output(t)).toContainText('Enter times');await clear(t);check(true,'23:30 plus two hours rolls into next day; invalid clock time rejected');});
add('timestamp-diff-calculator',async({tool:t,expect,check})=>{await fill(t,'A','2024-03-10T01:30:00-05:00');await fill(t,'B','2024-03-10T03:30:00-04:00');await expect(output(t)).toContainText('1');const vals=await t.locator('.tb-v2-stat-pill-val').allTextContents();check((await output(t).innerText()).includes('3,600')||(await output(t).innerText()).includes('3600'),'DST offset timestamp difference is exactly 3600 seconds');await fill(t,'A','not-a-date');await expect(t.getByText(/Could not parse the first/)).toBeVisible();await clear(t);});
add('fake-address-generator',async({tool:t,expect,check})=>{await example(t);const cards=t.locator('.tb-v2-card-content');const text=await t.innerText();check(/\b[A-Z]{2} \d{5}\b/.test(text),'Generated synthetic address includes state abbreviation and ZIP-shaped value');await expect(t.getByText(/sampled independently/)).toBeVisible();await clear(t);await expect(t.getByText('Full Address',{exact:true})).toHaveCount(0);});
add('css-animation-generator',async({tool:t,expect,check})=>{await example(t);await expect(t.locator('pre')).toContainText('@keyframes spin');await expect(t.locator('pre')).toContainText('animation: spin 2s linear');await clear(t);await expect(t.locator('pre')).toContainText('@keyframes fade-in');check(true,'Animation example and Clear produce corresponding keyframes and timing');});
add('css-cursor-generator',async({tool:t,page,expect,check})=>{const cursorImage=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=16;canvas.getContext('2d').fillRect(0,0,16,16);return canvas.toDataURL('image/png').split(',')[1];});await page.route("https://example.com/a'b.png",r=>r.fulfill({status:200,contentType:'image/png',body:Buffer.from(cursorImage,'base64')}));await example(t);await expect(t.locator('pre')).toContainText('cursor: crosshair;');await fill(t,'Image Url',"https://example.com/a'b.png");await expect(t.locator('pre')).toContainText('url("https://example.com/a\'b.png")');await clear(t);await expect(t.locator('pre')).toContainText('cursor: auto;');check(true,'Cursor CSS uses a quoted URL without breaking apostrophes');});
add('percentage-change-calc',async({tool:t,expect,check})=>{await click(t,'Change');await fill(t,'Old value','80');await fill(t,'New value','100');await expect(output(t)).toContainText('25');await fill(t,'Old value','0');await expect(t.getByText(/zero|non-zero|valid/i).last()).toBeVisible();await clear(t);check(true,'80 to 100 is a 25% increase; zero baseline cannot produce a finite change');});
add('random-choice-picker',async({tool:t,expect,check})=>{const resets=t.getByRole('button',{name:'Clear',exact:true});await expect(resets).toHaveCount(2);for(let i=0;i<2;i++){await fill(t,'List Text','Only choice');await click(t,/Pick/);await expect(output(t)).toContainText('Only choice');await resets.nth(i).click();await expect(t.getByLabel('List Text')).toHaveValue('');await expect(t.locator('.tb-v2-tool-output-body')).toHaveCount(0);await expect(t.getByRole('button',{name:/Pick/})).toBeDisabled();}check(true,'Single option is selected exactly; both existing Clear controls reset result/input and empty list disables picking');});
add('discount-calculator',async({tool:t,expect,check})=>{await fill(t,'Original price','100');await fill(t,'First discount percentage','20');await fill(t,'Additional discount percentage','10');await fill(t,'Sales tax percentage','5');await expect(output(t)).toContainText('$75.60');await fill(t,'First discount percentage','101');await expect(t.getByText(/between 0 and 100|0.*100/).last()).toBeVisible();await clear(t);check(true,'Successive discounts and post-discount tax: 100 × .8 × .9 × 1.05 = 75.60');});
add('word-combinations',async({tool:t,expect,check})=>{await t.getByRole('textbox').fill('red\nblue\ngreen');await click(t,'2-word');await expect(output(t).locator('.tb-v2-tool-pre')).toHaveText('red blue\nred green\nblue green');await click(t,/Permutations/);check((await output(t).locator('.tb-v2-tool-pre').innerText()).split('\n').length===6,'Three distinct words yield six ordered pairs');await clear(t);await expect(t.getByRole('textbox')).toHaveValue('');});
add('base64-file-encoder',async c=>{const {tool:t,expect,check}=c;await example(t);await expect(t.locator('pre')).toHaveText('SGVsbG8sIHdvcmxkIQo=');await click(t,'Decode');await fill(t,'Base64 input','SGVsbG8sIHdvcmxkIQo=');const b=await download(c,'Download decoded file');check(b.equals(Buffer.from('Hello, world!\n')),'Decoded download has exact original bytes');await expect(t.getByLabel('Base64 input')).toHaveValue('SGVsbG8sIHdvcmxkIQo=');await fill(t,'Base64 input','!invalid');await expect(t.getByRole('alert')).toBeVisible();await clear(t);await expect(t.getByLabel('Base64 input')).toHaveValue('');});
add('what-if-scenario-calculator',async({tool:t,expect,check})=>{await example(t);await expect(output(t)).toContainText('20,000');await fill(t,'Formula','-2^2');await expect(output(t)).toContainText('-4');await fill(t,'Formula','2^3^2');await expect(output(t)).toContainText('512');await fill(t,'Formula','1/0');await expect(t.getByText('Division by zero')).toBeVisible();await clear(t);check(true,'Arithmetic uses conventional exponent precedence and rejects division by zero');});
add('bill-splitter',async({tool:t,expect,check})=>{await example(t);await expect(output(t)).toContainText('$40.96');await expect(output(t)).toContainText('$23.04');await expect(output(t)).toContainText('$64.00');await clear(t);await fill(t,'Bill subtotal','10');await fill(t,'Number of people','3');await fill(t,'Tip percentage','0');await expect(output(t)).toContainText('$3.34');await expect(output(t)).toContainText('$3.33');check(true,'Custom tax/tip split and cent remainder allocation preserve the total');await clear(t);});
add('bmi-calculator',async({tool:t,expect,check})=>{await example(t);await expect(t.getByText('22.9',{exact:true})).toBeVisible();await fill(t,'Height','0');await expect(t.getByText(/greater than zero/)).toBeVisible();await clear(t);await expect(t.getByLabel('Height')).toHaveValue('');check(true,'70 kg / 1.75² rounds to 22.9 and zero height is rejected');});
export default cases;
